<?php
/**
 * @var $block \Mirasvit\LayeredNavigation\Block\Renderer\LabelRenderer
 * @var $escaper \Magento\Framework\Escaper
 */

$attributeCode  = $block->getAttributeCode();
$cacheKey       = rand(100000, 1000000);
$filterAccessor = $attributeCode . 'A' . $cacheKey . 'A';
$filter         = $block->getFilter();

$useAlphabeticalIndex = strpos(get_class($filter), 'AttributeFilter') !== false && $filter->isUseAlphabeticalIndex();

$checkedItemsCount = 0;

$letter  = '';
?>

<div data-mst-nav-filter="<?= $filterAccessor ?>" data-mst-nav-cache-key="<?= $cacheKey ?>" data-mst-attribute="<?= $attributeCode ?>" class="mst-nav__label" x-data="initLabelRenderer()">
    <?= $block->getSearchBoxElement($filterAccessor) ?>
    <div
        data-holder="alphabetical"
        x-data="initAlphabeticalIndex(<?= (int)($useAlphabeticalIndex && $filter->isAlphabeticalIndexAllowedByLimit()) ?>, <?= $filter->getAlphabeticalLimit() ?>)"
        x-init="init()"
    ></div>

    <ol class="items">
        <?php foreach ($block->getFilterItems() as $key => $filterItem):
            $label = $filterItem->getData('label');
            $numberOfResults = $filterItem->getData('count');

            $isItemChecked = $block->isFilterItemChecked($filterItem, true);

            $imageUrl         = $block->getImageUrl($filterItem);
            $isFullWidthImage = $block->isFullWidthImage($filterItem);

            if ($isItemChecked) {
                $checkedItemsCount++;
            }

            $cssClass = [
                'item',
                'mst-nav__label-item',
                '_mode-' . $block->getFilterItemDisplayMode($attributeCode),
                $isItemChecked ? '_checked' : '',
                $isItemChecked && $block->isHighlightEnabled() ? '_highlight' : '',
                $imageUrl ? '_image' : '',
                $imageUrl && $isFullWidthImage ? '_full-width' : '',
            ];
            ?>

            <?php if(
                $useAlphabeticalIndex
                && $filter->isSortByLabel()
                && $letter !== $block->getFirstLetter($label)
            ):
            $letter = $block->getFirstLetter($label);
            ?>
            <li class="mst-nav__letter mst-nav__label-item" data-letter="<?= $letter ?>" data-element = filter>
                <b><?= $letter ?></b>
            </li>
            <?php endif ?>

            <li data-element="filter"
                data-hidden="false"
                data-search-hidden="false"
                data-letter-hidden="false"
                class="<?= implode(' ', $cssClass) ?>"
                data-value="<?= $filterItem->getValueString() ?>"
                @click="handleClick"
                <?= $useAlphabeticalIndex ? 'data-letter="' .  $block->getFirstLetter($label) . '"' : '' ?>
            >
                <?php if ($numberOfResults >= 0): ?>
                    <?php
                    $url = $isItemChecked ? $filterItem->getRemoveUrl() : $filterItem->getUrl();
                    $id  = $block->getItemId($filterItem);
                    $final_url = $escaper->escapeUrl($url);
                    if (!str_contains($final_url, 'product_list_mode=list')) { 
                        $final_url .= "&product_list_mode=list";
                    }
                    ?>
                    <a href="<?= $final_url ?>"
                       rel="<?= $block->getRelAttributeValue() ?>"
                       aria-label="<?= $escaper->escapeHtmlAttr($label) ?>"
                    >
                        <?php if ($imageUrl): ?>
                            <div class="swatch-option image" style="background: url(<?= $imageUrl ?>) no-repeat center;  background-size: auto 100%;"></div>
                        <?php endif ?>

                        <input id="<?= $id ?>" type="checkbox" <?= $isItemChecked ? 'checked' : '' ?> />

                        <label for="<?= $id ?>">
                            <span class="mst-nav__label-item__label"><?= $label ?></span>
                            <?php if($block->getCountElement($filterItem)): ?>
                                <span class="count text-primary"><?= $filterItem->getData('count') ?></span>
                            <?php endif; ?>
                        </label>
                    </a>
                <?php else: ?>
                    <span class="mst-nav__label-item__label"><?= $label ?></span>
                    <?php if($block->getCountElement($filterItem)): ?>
                        <span class="count text-primary"><?= $filterItem->getData('count') ?></span>
                    <?php endif; ?>
                <?php endif ?>
            </li>
        <?php endforeach ?>

        <?= $block->getSizeLimiterElement($filterAccessor) ?>
    </ol>

    <div class="hidden mst-clear-options-link" data-checked-count="<?= $checkedItemsCount ?>">
        <div class="mst-nav__checked-counter__wrapper flex items-center mx-2">
            <div class="mst-nav__checked-counter rounded px-2 bg-gray-200 mr-1"><?= $checkedItemsCount ?></div>
            <a class="hover:underline text-2xl opacity-50" href="<?= $block->getAttributeClearUrl($attributeCode) ?>" data-element="filter">&#10005;</a>
        </div>
    </div>
</div>
