<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Sales\Block\Order\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */
?>
<?php foreach ($block->getTotals() as $_code => $_total) : ?>
    <?php if ($_total->getBlockName()) : ?>
        <?php //echo  $block->getChildHtml($_total->getBlockName(), false) ?>
    <?php else :?>
        <tr>
            <td colspan="5" bgcolor="#296497" class="quote-raq">
                <table width="100%" border="0" cellpadding="0" cellspacing="0" align="center"> 
                    <tr class="<?= $block->escapeHtmlAttr($_code) ?>">
                        <th <?= /* @noEscape */ $block->getLabelProperties() ?> scope="row" style="font-family:Open Sans, Arial, sans-serif;font-weight: 400;font-size: 14px;line-height: 20px;color: #FFFFFF;text-align: right !important;padding-top: 20px;"> 
                            <?php if ($_total->getStrong() || $_total->getLabel() == "Grand Total") : ?>
                                <strong style="font-family:Open Sans, Arial, sans-serif;font-weight: 700;font-size: 16px;line-height: 24px;color: #FFFFFF;text-align: right;padding-bottom: 20px;display: block !important;"><?= $block->escapeHtml($_total->getLabel()) ?></strong>
                            <?php else : ?>
                                <?= $block->escapeHtml($_total->getLabel()) ?>
                            <?php endif ?>
                        </th>
                        <td <?= /* @noEscape */ $block->getValueProperties() ?> data-th="<?= $block->escapeHtmlAttr($_total->getLabel()) ?>"  style="font-family:Open Sans, Arial, sans-serif;font-weight: 400;font-size: 14px;line-height: 20px;color: #FFFFFF;text-align: right !important;padding-top: 20px;padding-right: 33px;min-width: 220px!important;box-sizing: border-box !important;width: 220px!important;">
                            <?php if ($_total->getStrong() || $_total->getLabel() == "Grand Total") : ?>
                                <strong style="font-family:Open Sans, Arial, sans-serif;font-weight: 700;font-size: 16px;line-height: 24px;color: #FFFFFF;text-align: right;padding-bottom: 20px;display: block !important;"><?= /* @noEscape */ $block->formatValue($_total) ?></strong>
                            <?php else : ?>
                                <?= /* @noEscape */ $block->formatValue($_total) ?>
                            <?php endif?>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>    
    <?php endif; ?>
<?php endforeach?>

<script>
    jQuery('.amasty_quote-account-view .quote-item-notes + tfoot td').attr('colspan', '12');
</script>