<?php
/** @var \Magento\Checkout\Block\Cart\Item\Renderer $block */
$item = $block->getItem();
$product = $item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
// @codingStandardsIgnoreLine
$helper = $this->helper(\Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
/** @var \Amasty\RequestQuote\Helper\Cart $cartHelper */
// @codingStandardsIgnoreLine
$cartHelper = $this->helper(\Amasty\RequestQuote\Helper\Cart::class);
/** @var \Amasty\RequestQuote\Helper\Data $configHelper */
// @codingStandardsIgnoreLine
$configHelper = $this->helper(\Amasty\RequestQuote\Helper\Data::class);

$sampleProductBlock = $block->getLayout()->createBlock(\Dcw\SampleProduct\Block\SampleData::class);
?>
<div class="flex justify-start pb-11 border-gray-1 pt-2 later-cart">
    <div class="pt-6 pl-0 flex flex-nowrap flex-row prdct">
        <div class="cart-img-wrapper mr-5">
            <?php if ($block->hasProductUrl()): ?>
            <a href="<?= /* @noEscape */ $block->getProductUrl() ?>"
               title="<?= $escaper->escapeHtml($product->getName()) ?>"
               tabindex="-1"
               class="product-item-photo">
                <?php else: ?>
                <span class="product-item-photo">
            <?php endif; ?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()): ?>
            </a>
        <?php else: ?>
            </span>
        <?php endif; ?>
        </div>
        <div class="product-desc">
            <strong class="product-item-name break-all text-size16 font-semibold">
                <?php if ($block->hasProductUrl()): ?>
                    <a href="<?= /* @noEscape */ $block->getProductUrl() ?>">
                        <?= $escaper->escapeHtml($sampleProductBlock->getCartItemName($item)) ?>
                    </a>
                <?php else: ?>
                    <?= $escaper->escapeHtml($sampleProductBlock->getCartItemName($item)) ?>
                <?php endif; ?>
            </strong>
            <?php if ($options = $block->getOptionList()): ?>
                <dl class="item-options w-full break-all mt-8 clearfix">
                    <?php foreach ($options as $option): 
                        if ($option['label']=="Configurable Product Id" || 
                        $option['label']== "Configurable Product Url" || 
                        $option['label']=="Configurable Product Image" || 
                        $option['label'] == "Product Name") {
                            continue;
                        }
                    ?>
                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                        <?php if($option['label']!=""){?>
                            <dt class="text-size14 font-semibold float-left clear-left mr-2 mb-2"><?= $escaper->escapeHtml($option['label']) ?>:</dt>
							<?php }  else {?>
							<dt class="text-size14 font-semibold float-left clear-left mb-2 no-labels"></dt>
							<?php } ?>
                        <dd class="float-left text-size14">
                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                <?= /* @noEscape */ $_formatedOptionValue['full_view'] ?>
                            <?php else: ?>
                                <?= /* @noEscape */ $_formatedOptionValue['value'] ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif;?>
            <!--<div x-data="{ isOpen: false }">
                <p class="mb-0">
                    <a class="add-note-quote text-sm"
                      x-on:click="isOpen = !isOpen"
                    ><?= $escaper->escapeHtml(__('Add Note')) ?>
                    </a>
                </p>
                <div class="field textarea add-note"
                x-show="isOpen"
                >
                    <div class="control">
                    <textarea id="cart-<?= /* @noEscape */ $item->getId() ?>-note"
                              name="cart[<?= /* @noEscape */ $item->getId() ?>][note]"
                              data-cart-item-id="<?= $escaper->escapeHtml($item->getSku()) ?>"
                              rows="2"
                              class="border border-mystic-light"
                              cols="15"><?= $escaper->escapeHtml($cartHelper->retrieveCustomerNote($item->getAdditionalData())) ?></textarea>
                    </div>
                </div>
            </div>-->
            <?php if ($messages = $block->getMessages()): ?>
                <?php foreach ($messages as $message): ?>
                    <div class="cart item message <?= /* @noEscape */ $message['type'] ?>"><div><?= $escaper->escapeHtml($message['text']) ?></div></div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock): ?>
                <?= $addInfoBlock->setItem($item)->toHtml() ?>
            <?php endif;?>
        </div>
    </div>
    <div class="pt-6 px-4 items-center prc">
        <div class="flex flex-col lg:flex-row items-center justify-center text-sm sm:text-base">
            <?php if ($canApplyMsrp): ?>
                <span class="block text-left md:text-right lg:text-center lg:whitespace-nowrap">
                    <span class="msrp notice"><?= /* @noEscape */ __('See price before order confirmation.') ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $item->getId(); ?>
                    <a href="#" class="action help map" id="<?= /* @noEscape */ ($helpLinkId) ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?= /* @noEscape */ $helpLinkId ?>","productName": "<?= /* @noEscape */ $product->getName() ?>","showAddToCart": false}}'>
                        <span><?= /* @noEscape */ __("What's this?") ?></span>
                    </a>
                </span>
            <?php else: ?>
                <span class="quote-custom-price block text-left md:text-right lg:text-center lg:whitespace-nowrap">
                    <?= $block->getUnitPriceHtml($item) ?>
                </span>
            <?php endif; ?>
        </div>
    </div>
    <div class="pt-5 px-4 justify-center qnty">
        <div class="flex items-center lg:justify-center">
            <div class="block text-center flex-col lg:flex-row items-center qty">
                <input id="cart-<?= /* @noEscape */ $item->getId() ?>-qty"
                       name="cart[<?= /* @noEscape */ $item->getId() ?>][qty]"
                       data-cart-item-id="<?= $escaper->escapeHtml($item->getSku()) ?>"
                       value="<?= /* @noEscape */ $block->getQty() ?>"
                       type="text"
                       size="4"
                       onkeypress="return onlyNumberKey(event)"
                       onblur="submitForm(event)"
                       title="<?= $escaper->escapeHtml(__('Qty')) ?>"
                       <?= ($product->getFreeTshirt() == 1)?'readonly disabled':''; ?>
                       class="input-text qty form-input px-2 py-2 w-20 text-center" />
            </div>
        </div>
    </div>
    <div class="pt-6 px-4 items-center sbtl">
        <div class="flex sm:items-center sm:justify-center lg:justify-end sm:text-base items-center">
            <div class="flex items-center sm:justify-center">
                <span class="block text-left md:text-right lg:text-center lg:whitespace-nowrap">
                    <?php if ($canApplyMsrp): ?>
                        <span class="cart msrp subtotal">--</span>
                    <?php else: ?>
                        <?php if ((float) $item->getPrice() || $configHelper->isAllowCustomizePrice()): ?>
                            <?= $block->getRowTotalHtml($item) ?>
                        <?php else: ?>
                            <?= $escaper->escapeHtml('N/A') ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </span>
            </div>
        </div>
    </div>
	
	<div class="item-actions quotes-cart">
    <div class="req-cart-contents">
        <div class="actions-toolbar q-carts">
            <?= /* @noEscape */ $block->getActions($item) ?>
        </div>
    </div>
	</div>
</div>

<script>
        function onlyNumberKey(evt) {
             
            // Only ASCII character in that range allowed
            var ASCIICode = (evt.which) ? evt.which : evt.keyCode
            if (ASCIICode > 31 && (ASCIICode < 48 || ASCIICode > 57))
                return false;
            return true;
        }
    </script>
    <script>
        var myForm = document.getElementById("form-validate");
        function submitForm(){
				window.dispatchEvent(new CustomEvent('amcart-loading-start'));
					cart_id = <?= $item->getId(); ?>,
                    postUrl = '<?= $escaper->escapeUrl($block->getUrl('amasty_quote/cart/updatePost')) ?>',
                    formKey = document.querySelector('input[name=form_key]').value,
                    form = document.getElementById('form-validate');

                    form.onSubmit = function onSubmit(e) {
                        e.preventDefault();
                    }

                    let data = new URLSearchParams(new FormData(form)).toString() + '&update_cart_action=update_qty';

                    fetch(postUrl, {
                        "headers": {
                            "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                            "X-Requested-With": "XMLHttpRequest"
                        },
                        "method": "POST",
                        "mode": "cors",
                        "credentials": "include",
                        "body": new URLSearchParams(data)
                    }).then((response) => {
                        return response.json();
                    }).then((responseData) => {
						window.dispatchEvent(new CustomEvent('amcart-loading-stop'));
                        window.location.reload();
                    })
                        .catch((err) => {
                            console.log('Error message:', err);
                        })
        }
        function detailssubmit() {
            alert("Your details were Submitted");
        }
    </script>