<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Email\Items */
?>
<?php $_order = $block->getOrder() ?>
<?php if ($_order) : ?>
    <?php $_items = $_order->getAllItems(); ?>
    <table class="email-items" border="0" width="100%" cellpadding="0" cellspacing="0" align="center" bgcolor="#DCE5EC">
        <thead>
            <tr>
                <th width="30">&nbsp;</th>
                <th class="item-info" style="font-family:Open Sans, Arial, sans-serif !important;font-weight: 700;font-size: 16px;line-height: 24px;color: #000000;text-align: left;">
                    <span style="display: block !important;border-bottom: 1px solid #CFCFCF;padding-bottom: 10px;"><?= $block->escapeHtml(__('Items')) ?></span>
                </th>
                <th class="item-qty" style="font-family:Open Sans, Arial, sans-serif !important;font-weight: 700;font-size: 16px;line-height: 24px;color: #000000;text-align: center;width:100px;min-width: 100px;">
                    <span style="display: block !important;border-bottom: 1px solid #CFCFCF;padding-bottom: 10px;"><?= $block->escapeHtml(__('Qty')) ?></span>
                </th>
                <th class="item-price" style="font-family:Open Sans, Arial, sans-serif !important;font-weight: 700;font-size: 16px;line-height: 24px;color: #000000;text-align: right;width: 120px;min-width: 120px;box-sizing: border-box !important;">
                    <span style="display: block !important;border-bottom: 1px solid #CFCFCF;padding-bottom: 10px;"><?= $block->escapeHtml(__('Subtotal')) ?></span>
                </th>
                <th width="30">&nbsp;</th>
            </tr>
        </thead>
        <?php foreach ($_items as $_item) : ?>
            <?php if (!$_item->getParentItem()) : ?>
                <tbody>
                    <?= $block->getItemHtml($_item) ?>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
        <tfoot class="order-totals" style="background: #296497 !important;">
            <?= $block->getChildHtml('order_totals') ?>
        </tfoot>
    </table>
    <?php if ($this->helper(\Magento\GiftMessage\Helper\Message::class)
            ->isMessagesAllowed('order', $_order, $_order->getStore())
        && $_order->getGiftMessageId()
    ) : ?>
        <?php $_giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)
            ->getGiftMessage($_order->getGiftMessageId()); ?>
        <?php if ($_giftMessage) : ?>
            <br />
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= $block->escapeHtml(__('Gift Message for this Order')) ?></h3>
                        <strong><?= $block->escapeHtml(__('From:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br /><strong><?= $block->escapeHtml(__('To:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br /><strong><?= $block->escapeHtml(__('Message:')) ?></strong>
                        <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
