<?php
/** @var \Amasty\RequestQuote\Block\Cart\Quote\Move $block */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$cart = $objectManager->get('\Magento\Checkout\Model\Cart'); 
$itemId = $cart->getQuote()->getId();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
?>
<script>
    function moveCartToQuote() {  
        return {
			moveToQuoteLink: window.BASE_URL + 'amasty_quote/move/inQuote',
            moveQuotes() {
				document.getElementById("checkoutLoading").style.display = "block";
				fetch(this.moveToQuoteLink, {
                "headers": {
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                },
                "body": "form_key=" + document.querySelector('input[name=form_key]').value,
                "method": "POST",
                "mode": "cors",
                "credentials": "include",
            }).then(function (response) {
				if (response.redirected) {
                    // window.location.href = response.url;
					<?php if($customerSession->isLoggedIn()) { ?>
						cart_id = <?= $itemId; ?>,
						postUrl = '<?= $escaper->escapeUrl($block->getUrl('amasty_quote/cart/updatePost')) ?>',
						formKey = document.querySelector('input[name=form_key]').value,
						form = document.getElementById('form-validate');
						let data = new URLSearchParams(new FormData(form)).toString() + '&update_cart_action=submit&checkout=context';
						fetch(postUrl, {
							"headers": {
								"content-type": "application/x-www-form-urlencoded; charset=UTF-8",
								"X-Requested-With": "XMLHttpRequest"
							},
							"method": "POST",
							"mode": "cors",
							"credentials": "include",
							"body": new URLSearchParams(data)
						}).then((response) => {
							return response.json();
						}).then((responseData) => {
							document.getElementById("checkoutLoading").style.display = "none";
							window.dispatchEvent(new CustomEvent('amcart-loading-stop'));
							window.location.href = '<?= $escaper->escapeUrl($block->getUrl('amasty_quote/quote/success/')) ?>'
						})
					<?php }  else {?>
						document.getElementById("checkoutLoading").style.display = "none";
						window.location.href = window.BASE_URL + 'request_quote/cart/#checkoutLaterEmail';
					<?php } ?>
                    }
            }).then(function (response) {
                 let reloadCustomerDataEvent = new CustomEvent("reload-customer-section-data");
                 window.dispatchEvent(reloadCustomerDataEvent);
            });
			
        }
    }
	}
</script>
    <button
    class="amquote-addto-button amasty-quote-link btn btn-secondary-large w-full justify-center"
    x-data="moveCartToQuote()"
    x-on:click="moveQuotes()"
    ><?= $escaper->escapeHtml(__('Checkout Later')) ?>
    </button>
<div id="checkoutLoading" style="display:none" class="checkout-later-loading"></div>