<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package FAQ and Product Questions Hyva
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Amasty\Faq\Block\Widgets\Categories;
use Amasty\Faq\Api\Data\CategoryInterface;
use Amasty\Faq\Api\Data\QuestionInterface;
use Magento\Framework\Escaper;

/** @var ViewModelRegistry $viewModels */
/** @var Categories $block */
/** @var CategoryInterface $category */
/** @var QuestionInterface $question */
/** @var Escaper $escaper */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
// phpcs:disable Generic.Files.LineLength.TooLong
?>
<?php if ($categories = $block->getCategories()): ?>
    <div class="<?= $block->escapeHtml($block->getLayoutType()) ?> widget flex flex-wrap">
        <?php foreach ($categories as $category): ?>
            <div class="am-widget-category px-5 pb-5 w-full">
                <div class="am-category-container">
                    <div class="am-category-header flex items-center mb-4 hidden">
                        <?php if ($block->canShowCategoryIcon($category)): ?>
                            <div class="mr-2">
                                <img src="<?= $block->escapeUrl($block->getCategoryIconUrl($category)) ?>"
                                    width="50" height="50"
                                    alt="<?= $block->escapeHtml($category->getIcon()) ?>">
                            </div>
                        <?php endif ?>
                        <div class="text-md md:text-lg font-semibold">
                            <?= $block->escapeHtml($category->getTitle()) ?>
                        </div>
                        </div>
                        <div class="am-category-header items-center mb-4 block text-center">
                            <div class="text-size24 sm:text-size18 faq-headtitle block pb-1 pt-4">FAQs</div>
                            <div class="text-size36 sm:text-size24 faq-asked block font-semibold pb-2">Frequently Asked Questions</div>
                            <div class="text-size18 sm:text-size16 faq-question block pb-4">Have questions? We’re here to help</div>
                        </div>
                    <?php if (!$block->isShowWithoutQuestions()
                            && $questions = $block->getCategoryQuestions($category)): ?>
                        <div class="amfaq_questions">
                            <?php foreach ($questions as $question): ?>
                                <?php $uniqueId = '_' . uniqid() ?>
                                <div
                                    class="border-container border-b mb-4 pb-4"
                                    x-data="{ selected: null }"
                                >
                                    <button
                                            type="button"
                                            class="amquestion-title w-full text-left text-lg font-light cursor-pointer flex justify-between items-start"
                                            :class="{'opened-question': selected === 1}"
                                            @click="selected !== 1 ? selected = 1 : selected = null"
                                    >
                                        <span class="question-text">
                                            <?= $block->escapeHtml($question->getTitle()) ?>
                                        </span>
                                        <img src="<?php echo $this->getViewFileUrl('images/arrow-back.svg'); ?>"  width="24" height="24" alt="arrow-back" class="">
                                    </button>
                                    <div
                                        class="text-base relative
                                                overflow-hidden transition-all max-h-0 duration-300"
                                        x-ref="container<?= $escaper->escapeHtmlAttr($uniqueId) ?>"
                                        x-bind:style="selected == 1 ?
                                            'max-height: max-content' : ''"
                                    >
                                        <div class="mt-4 faq-content">
                                            <?= /** @noEscape */ $block->getShortAnswer($question) ?>
                                        </div>
                                        <div>
                                            <?php if (!$question->isShowFullAnswer()): ?>
                                                <a
                                                    href="<?= $block->escapeUrl($block->getQuestionUrl($question)) ?>"
                                                    class="text-blue-600 hover:underline text-sm"
                                                >
                                                    <?= $block->escapeHtml(__('Read More')) ?>
                                                </a>
                                            <?php endif ?>
                                        </div>
                                    </div>
                                </div>
                            <?php endforeach ?>
                        </div>
                    <?php endif ?>
                    <div class="text-right">
                        <a
                            href="<?= $block->escapeUrl($block->getCategoryUrl($category)) ?>"
                            class="text-blue-600 hover:underline text-sm"
                        >
                            <?= $block->escapeHtml(__('View all')) ?>
                        </a>
                    </div>
                </div>
            </div>
        <?php endforeach ?>
    </div>
<?php endif ?>

<?php if ($block->isAddStructuredData()): ?>
    <?= /** @noEscape */ $block->getCategoriesStructuredDataHtml() ?>
<?php endif ?>


