<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2022 Amasty (https://www.amasty.com)
 * @package Request a Quote Base for Magento 2
 */
?>
<?php
/**
 * @var \Amasty\RequestQuote\Block\Account\Quote\History $block
 * @var \Magento\Framework\Escaper $escaper
 */

$quotes = $block->getQuotes();
?>

<?= $block->getChildHtml('info') ?>
<?php if ($quotes && $quotes->getSize()): ?>
    <div class="table-wrapper quotes-history">
        <table class="data table table-quote-items history w-full" id="my-quotes-table">
            <!-- <caption class="table-caption"><?= $escaper->escapeHtml(__('Quotes')) ?></caption> -->
            <thead>
            <tr>
                <th scope="col" class="col id text-left text-size18 font-semibold text-black"><?= $escaper->escapeHtml(__('Cart #')) ?></th>
                <th scope="col" class="col date text-left text-size18 font-semibold text-black"><?= $escaper->escapeHtml(__('Date')) ?></th>
                <th scope="col" class="col total text-left text-size18 font-semibold text-black"><?= $escaper->escapeHtml(__('Cart Total')) ?></th>
                <!-- <th scope="col" class="col status"><?= $escaper->escapeHtml(__('Status')) ?></th> -->
                <?php /* if ($block->isExpiryColumnShow()): ?>
                <th scope="col" class="col expired"><?= $escaper->escapeHtml(__('Expiry Date')) ?></th>
                <?php endif; */ ?>
                <th scope="col" class="col actions text-left text-size18 font-semibold text-black"><?= $escaper->escapeHtml(__('Action')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($quotes as $quote): ?>
                <tr>
                    <td data-th="<?= $escaper->escapeHtml(__('Cart #')) ?>" class="col id text-left text-size14 font-normal text-thingray"><?= $escaper->escapeHtml($quote->getIncrementId()) ?></td>
                    <td data-th="<?= $escaper->escapeHtml(__('Date')) ?>" class="col date text-left text-size14 font-normal text-thingray"><?= $escaper->escapeHtml($block->formatDate($quote->getCreatedAt())) ?></td>
                    <td data-th="<?= $escaper->escapeHtml(__('Cart Total')) ?>" class="col total text-left text-size14 font-normal text-thingray"><?= /* @noEscape */ $quote->formatPrice($quote->getGrandTotal()) ?></td>
                    <!--- <td data-th="<?= $escaper->escapeHtml(__('Status')) ?>" class="col status"><?= $escaper->escapeHtml($quote->getStatusLabel())?></td> -->
                    <?php /* if ($block->isExpiryColumnShow()): ?>
                    <td data-th="<?= $escaper->escapeHtml(__('Expiry Date')) ?>" class="col expired"><?= $escaper->escapeHtml($block->getExpiredDate($quote)) ?></td>
                    <?php endif; */ ?>
                    <td data-th="<?= $escaper->escapeHtml(__('Actions')) ?>" class="col actions text-left text-size14 font-normal text-thingray">
                        <a href="<?= $escaper->escapeUrl($block->getViewUrl($quote)) ?>" class="action view text-black underline">
                            <span><?= $escaper->escapeHtml(__('View')) ?></span>
                        </a>
						
                    <?php  if ($block->isMoveShowed($quote)): ?>
					<div x-data="">
						<button x-on:click="submitData('<?=$block->getMoveUrl($quote)?>')"><?= $escaper->escapeHtml(__('Move to Cart')) ?></button>
					</div>
                    <?php endif; ?>
                    </td>
                </tr> 
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="quote-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?= $escaper->escapeHtml(__('You have placed no quotes.')) ?></span></div>
<?php endif ?>
<script>
  function submitData(url) {
    //const myDataJSON = JSON.stringify(this.myData);
	 const formKey = hyva.getFormKey();
     window.dispatchEvent(new CustomEvent('amcart-loading-start'));
console.log(formKey);
    fetch(url, {
      method: 'POST',
      "headers": {
                        "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    },
      body:"uenc=" + formKey+"&form_key=" + formKey,
    })
    .then(response => {
      // Handle the response from the server
      window.dispatchEvent(new CustomEvent('amcart-loading-stop'));
      console.log(response);
	  location.reload();
    })
    .catch(error => {
      // Handle any errors that occur
      console.error(error);
	  location.reload();
    });
  }

  
</script>