<?php
$objectManager      = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get(\Magento\Store\Model\StoreManagerInterface::class);
$desktop_limit = $objectManager->get(\Magento\Framework\App\Config\ScopeConfigInterface::class)
->getValue('dcw_home_page/shopbycategory/desktop_limit', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
if (empty($desktop_limit)) {
    $desktop_limit = 50;
}
$place_holder_img = $objectManager->get(\Magento\Framework\App\Config\ScopeConfigInterface::class)
->getValue('catalog/placeholder/thumbnail_placeholder', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);

$mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$place_holder_img_src =  $mediaUrl.'catalog/product/'.$place_holder_img;
$categoryCollection = $objectManager
    ->get(\Magento\Catalog\Model\ResourceModel\Category\CollectionFactory::class);
$categories = $categoryCollection->create();
$categories->addAttributeToSelect('*');
$categories->addAttributeToFilter('featured_categories', 1);
$no_of_item = $categories->count();

?>
<?php if($no_of_item > 0){ ?>
<div class="heading_shop_by_cat">Shop By Category</div>
<div class="outer shopbycategory" x-data="shopbyCategoryAjaxCall()" x-init="initShopbyCategoryFunc()">
    <div class="inner">
        <template x-for="item in categories.items">
            <div class="category_box">
                <a x-bind:href="BASE_URL+item.url_path+item.url_suffix">
					<template x-if="item.image">
						<img  x-bind:src="item.image+'?width=200'" alt="category-image" title="category-image" />
					</template>
                    <template x-if="!item.image">
						<img  src="<?= /* @noEscape */ $place_holder_img_src;?>?width=200" alt="category-image" title="category-image" />
					</template>
                    <div x-html="item.name"></div>
                </a>
            </div>
        </template>
    </div>
</div>

<?php
$body_data = '{categories(filters: {featured_categories: {eq:1}} pageSize:'.$desktop_limit.')'.
'{items{name image url_path url_suffix}}}';
?>
<script>
  function shopbyCategoryAjaxCall() {
    return {
        categories:'',
        initShopbyCategoryFunc: function () {
            fetch(BASE_URL+'graphql?form_key=' + hyva.getFormKey(), {
                method: "POST",
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ query:'<?= /* @noEscape */ $body_data?>'}),
            })
            .then(response => {
                if (! response.ok) console.warn('GET request failed');
                return response.json();
            })
            .then(data => {
                if (data) {
                  this.categories = data.data.categories;
                }
            });
        }
    }
  }
</script>
<?php } ?>