<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Theme\Block\Html\Breadcrumbs;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Breadcrumbs $block */
/** @var array[] $crumbs */

?>
<?php if ($crumbs && is_array($crumbs)): ?>
<nav class="breadcrumbs order-2 w-full" aria-label="Breadcrumb">
    <div class="breadcrumbs-in py-8">
        <ol class="items list-reset rounded flex flex-wrap text-grey text-sm">
            <?php foreach ($crumbs as $crumbName => $crumbInfo): ?>
                <li class="item flex <?= $escaper->escapeHtmlAttr($crumbName) ?>">
                <?php if (!$crumbInfo['first']): ?>
                    <span aria-hidden="true" class="separator text-primary-lighter px-2 text-sm font-normal">/</span>
                <?php endif; ?>
                <?php if ($crumbInfo['link']): ?>
                    <a href="<?= $escaper->escapeUrl($crumbInfo['link']) ?>"
                       class="no-underline text-sm font-normal"
                       title="<?= $escaper->escapeHtmlAttr($crumbInfo['title']) ?>"
                    ><?= $escaper->escapeHtml($crumbInfo['label']) ?></a>
                <?php elseif ($crumbInfo['last']): ?>
                    <a href="<?= $escaper->escapeUrl($crumbInfo['link']) ?>"
                       class="text-sm font-semibold current"
                       aria-current="page"
                    ><?= $escaper->escapeHtml($crumbInfo['label']) ?></a>
                <?php else: ?>
                    <?= $escaper->escapeHtml($crumbInfo['label']) ?>
                <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
</nav>
<?php endif; ?>
