<?php
$objectManager      = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get(\Magento\Store\Model\StoreManagerInterface::class);
$mobile_limit = $objectManager->get(\Magento\Framework\App\Config\ScopeConfigInterface::class)
->getValue('dcw_home_page/shopbycategory/mobile_limit', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
if (empty($mobile_limit)) {
    $mobile_limit = 50;
}
$place_holder_img = $objectManager->get(\Magento\Framework\App\Config\ScopeConfigInterface::class)
->getValue('catalog/placeholder/thumbnail_placeholder', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);

$mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$place_holder_img_src =  $mediaUrl.'catalog/product/'.$place_holder_img;

$categoryCollection = $objectManager
    ->get(\Magento\Catalog\Model\ResourceModel\Category\CollectionFactory::class);
$categories = $categoryCollection->create();
$categories->addAttributeToSelect('*');
$categories->addAttributeToFilter('featured_categories', 1);
$no_of_item = $categories->count();
?>

<?php if($no_of_item > 0){ ?>
<div class="heading_shop_by_cat">Shop By Category</div>
<div class="outer shopbycategory" x-data="shopbyCategoryAjaxCall()" x-init="initShopbyCategoryFunc()">
    <div class="inner" :class="{ 'crossed': categoriesItemCount > 8 }">
        <template x-for="item in categories.items">
            <div class="category_box">
                <a x-bind:href="BASE_URL+item.url_path+item.url_suffix">
                    <img x-show="item.image" x-bind:src="item.image+'?width=155'" alt="category-image" title="category-image" />
                    <img x-show="!item.image" src="<?= /* @noEscape */ $place_holder_img_src;?>" alt="category-image" title="category-image" />
                    <div x-html="item.name"></div>
                </a>
            </div>
        </template>
        <a class="underline text-center text-size14 font-medium text-black w-full"
           x-on:click="document.querySelector('.inner').classList.remove('crossed');
           document.querySelector('.inner').classList.add('limited')">Show All</a>
    </div>
</div>
<?php
$body_data = '{categories(filters: {featured_categories: {eq:1}} pageSize:'.$mobile_limit.')'.
'{items{name image url_path url_suffix}}}';
?>
<script>
  function shopbyCategoryAjaxCall() {
    return {
        categories:'',
        categoriesItemCount:0,
        initShopbyCategoryFunc: function () {
            fetch(BASE_URL+'graphql?form_key=' + hyva.getFormKey(), {
                method: "POST",
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ query:'<?= /* @noEscape */ $body_data?>'}),
            })
            .then(response => {
                if (! response.ok) console.warn('GET request failed');
                return response.json();
            })
            .then(data => {
                if (data) {
                  this.categories = data.data.categories;
                  this.categoriesItemCount = data.data.categories.items.length;
                }
            });
        }
    }
  }
</script>
<?php } ?>
