<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Theme\Block\Html\Title;

/** @var Escaper $escaper */
/** @var Title $block */

$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : 'text-3xl';
$titleHtml = '';
if (trim((string)$block->getPageHeading())) {
    $titleHtml = '<span class="base" data-ui-id="page-title-wrapper" '
        . $block->getAddBaseAttribute()
        . '>'
        . $escaper->escapeHtml($block->getPageHeading())
        . '</span>';
}
?>
<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('\Magento\Framework\App\Request\Http');
$actionfullname = $request->getFullActionName();

?>
<?php if ($titleHtml): ?>
<div class="container flex flex-col md:flex-row flex-wrap font-bold">
    <h1 class="text-gray-900 page-title title-font"
        <?php if ($block->getId()): ?> id="<?= $escaper->escapeHtmlAttr($block->getId()) ?>" <?php endif; ?>>
        <?php if ($actionfullname =="amasty_quote_account_view"){
					echo  str_replace("Quote","Cart Id",$titleHtml);
					
		} else {?>
				<?= /* @noEscape */ $titleHtml ?>
		<?php } ?>
    </h1>
    <?= $block->getChildHtml() ?>
</div>
<?php endif; ?>
