<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\LoginAsCustomerFrontendUi\ViewModel\Configuration;

/**
 * @var Template $block
 * @var Escaper $escaper
 * @var ViewModelRegistry $viewModels
 */
$viewFileUrl = $block->getViewFileUrl('Magento_LoginAsCustomerFrontendUi::images/magento-icon.svg');

/** @var Configuration $configurationViewModel */
$configurationViewModel = $viewModels->require(Configuration::class);
if (!$configurationViewModel->isEnabled()) {
    return;
}
?>
<?php
$notificationtext='';
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$glob_notif_3 = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('dcw_notifications_config/notification3/notification3_text');
$resp_arr["glob_notif_3"] = $glob_notif_3;
$request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
$resp_arr["full_action_name"] = $request->getFullActionName();

if ($resp_arr['full_action_name'] == 'catalog_category_view') {
    $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category'); //get current category
    $categoryId = $category->getId();
    $category2 = $objectManager->create('Magento\Catalog\Model\Category')->load($categoryId);
    $cat_arr = $category2->getdata();
    if (isset($cat_arr['category_notification_bar3'])) {
        $resp_arr["category_notification_bar3"] = $cat_arr['category_notification_bar3'];
    } else {
        $resp_arr["category_notification_bar3"] = "";
    }
    
}

if ($resp_arr['full_action_name'] == 'catalog_product_view') {
    $product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current product
    $product2 = $objectManager->create('Magento\Catalog\Model\Product')->load($product->getId());
    $resp_arr["product_notification_bar3"] = $product2->getData('product_notification_bar3');
}

if ($resp_arr['full_action_name'] == 'catalog_product_view' || $resp_arr['full_action_name'] == 'catalog_category_view') {
    if ($resp_arr['full_action_name'] == 'catalog_category_view') {
        $notificationtext= $resp_arr['category_notification_bar3'];
    }

    if ($resp_arr['full_action_name'] == 'catalog_product_view') {
        $notificationtext= $resp_arr['product_notification_bar3'];
    }
} else {
    $notificationtext= $resp_arr['glob_notif_3'];
}
?>
<?php if ($notificationtext!=''): ?>
<div x-cloak class="notification3 bg-orange text-center pt-3 pb-3 text-center text-size13 font-medium text-thickblack w-full order-2"
     x-data="initLoginAsCustomer()"
     @private-content-loaded.window="receiveCustomerData(event.detail.data)"
>
    <div x-show="isVisible">
        <div>
    <?=$block->escapeHtml(__($notificationtext));?>
        </div>
    </div>
</div>
<?php endif;?>
<script>
    "use strict";

    function initLoginAsCustomer() {
        return {
            isVisible: false,
            adminUserId: null,
            websiteName: null,
            fullname: null,
            notificationText: '',
            receiveCustomerData: function receiveCustomerData(data) {
                if (data.customer) {
                    this.fullname = data.customer.fullname;
                }

                if (data.loggedAsCustomer) {
                    this.adminUserId = data.loggedAsCustomer.adminUserId;
                    this.websiteName = data.loggedAsCustomer.websiteName;
                }

                this.updateBanner();
            },

            updateBanner: function updateBanner() {
                this.isVisible = !!this.adminUserId;

                if (this.fullname !== undefined && this.websiteName !== undefined) {
                    this.notificationText = '<?=
                        $escaper->escapeHtml(__('You are connected as <strong>%1</strong> on %2'), ['<strong>']) ?>'
                        .replace('%1', this.fullname)
                        .replace('%2', this.websiteName);
                }
            }
        }
    }
</script>
<style>
    .product_lebel_container.margin_percentage_div {
        display: block !important;
    }
</style>
