<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package FAQ and Product Questions Hyva
 */

declare(strict_types=1);

use Amasty\Faq\Block\Lists\TagList;
use Magento\Framework\Escaper;

/** @var TagList $block */
/** @var Escaper $escaper */

$currentTag = $block->getCurrentTag();
if ($tags = $block->getTags()): ?>
<div class="card">
<h3 class="flex justify-between items-center cursor-pointer
                        md:cursor-default md:border-container md:border-b md:pb-4">
    <span class="title text-md md:text-lg font-semibold"><?= $escaper->escapeHtml(__('Tags')) ?></span>
    </h3>
    <div class="tags-card flex flex-wrap gap-2">
    <?php foreach ($tags as $tag): ?>
        <span class="<?= ($tag->getTitle() == $currentTag) ? ' ' : '' ?>">
            <a class="hover:underline mt-1 text-sm text-custom-blue font-semibold" href="<?= $escaper->escapeUrl($block->getTagLink($tag->getTitle())) ?>">
                <?= $escaper->escapeHtml($tag->getTitle()) ?>
                (<?= (int)$tag->getCount() ?>)
            </a>
        </span>
    <?php endforeach ?>
    </div>
</div>
<?php endif ?>
