<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $_item->getOrder();
?>
<tr>
    <td width="30">&nbsp;</td>
    <td class="item-info<?= ($block->getItemOptions() ? ' has-extra' : '') ?>" valign="top" style="font-family:Open Sans, Arial, sans-serif !important;font-weight: 600;font-size: 14px;line-height: 20px;color: #000000;text-align: left;padding-top: 10px !important;padding-bottom: 38px !important;">
        <p style="font-family:Open Sans, Arial, sans-serif !important;font-weight: 600;font-size: 14px;line-height: 20px;color: #000000;margin: 0 0 14px 0 !important;width: 210px;" class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <!-- <p style="font-family:Open Sans, Arial, sans-serif !important;font-weight: 400;font-size: 14px;line-height: 20px;color: #000000;margin: 0 0 14px 0 !important;width: 210px;" class="sku"></?= $block->escapeHtml(__('SKU')) ?>: </?= $block->escapeHtml($block->getSku($_item)) ?></p> -->
        <?php if ($block->getItemOptions()) : ?>
            <dl class="item-options" style="margin: 0 !important;display: inline-block !important;width: 100% !important;">
            <?php foreach ($block->getItemOptions() as $option) : ?>
                <div style="margin: 0 0 4px 0 !important;display: inline-block !important;width: 100% !important;clear: both !important;">
                <?php
                    if($option['label']!="") {
                ?>
                    <dt style="float: left !important;padding: 0 2px 0 0 !important;font-family:Open Sans, Arial, sans-serif !important;font-weight: 400 !important;font-size: 13px !important;line-height: 20px !important;color: #000000 !important;"><strong style="font-weight: 400 !important;"><em style="font-style: normal !important;"><?= $block->escapeHtml($option['label']) ?>:</em></strong></dt>
                <?php } ?>        
                    <dd style="float: left !important;box-sizing: border-box !important;margin: 0 !important;font-family:Open Sans, Arial, sans-serif !important;font-weight: 400 !important;font-size: 13px !important;line-height: 20px !important;color: #000000 !important;">
                        <?= /* @noEscape */  nl2br($block->escapeHtml($option['value'])) ?>
                    </dd>
                </div>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-qty" valign="top" style="font-family:Open Sans, Arial, sans-serif !important;font-weight: 600;font-size: 14px;line-height: 20px;color: #000000;text-align: center;padding-top: 10px !important;padding-bottom: 38px !important;"><?= (float) $_item->getQtyOrdered() ?></td>
    <td class="item-price" valign="top" style="font-family:Open Sans, Arial, sans-serif !important;font-weight: 600;font-size: 14px;line-height: 20px;color: #000000;text-align: right;padding-top: 10px !important;padding-bottom: 38px !important;">
        <?= /* @noEscape */ $block->getItemPrice($_item) ?>
    </td>
    <td width="30">&nbsp;</td>
</tr>
<?php if ($_item->getGiftMessageId()
    && $_giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)
        ->getGiftMessage($_item->getGiftMessageId())
) : ?>
    <tr>
    <td colspan="3" class="item-extra">
        <table class="message-gift">
            <tr>
                <td>
                    <h3><?= $block->escapeHtml(__('Gift Message')) ?></h3>
                    <strong><?= $block->escapeHtml(__('From:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                    <br /><strong><?= $block->escapeHtml(__('To:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                    <br /><strong><?= $block->escapeHtml(__('Message:')) ?></strong>
                    <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                </td>
            </tr>
        </table>
    </td>
</tr>
<?php endif; ?>
