<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Hyva_BssSocialLogin
 * @author     Extension Team
 * @copyright  Copyright (c) 2022 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
//  @codingStandardsIgnoreFile

use Magento\Framework\Escaper;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\BssSocialLogin\ViewModels\Helper as ModuleViewModel;

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$moduleViewModel = $viewModels->require(ModuleViewModel::class);
$checkButtonLogin = $moduleViewModel->checkButtonLogin();
?>
<div class="block-customer-login for_got" x-show="openForgot">
    <h2 id="authenticate-customer-login" class="text-size18 font-medium text-darkblack">
        <?= $escaper->escapeHtml(__('Forgot Password')) ?>
    </h2>
    <form class="form form-fotgotpassword"
          method="post"
          @submit.prevent="submitForgotForm();"
          id="fotgot-form">
        <fieldset class="fieldset">
            <div class="text-size14 font-normal text-black mb-4"><?= $escaper->escapeHtml(
                    __('Please enter your email address below to receive a password reset link.')
                ) ?></div>
            <div class="field email required">
                <label for="email_address" class="label"><span><?= $escaper->escapeHtml(
                            __('Email')
                        ) ?></span></label>
                <div class="control">
                    <input type="email" name="email" alt="email" id="email_address" class="form-input" required
                           value="">
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action submit primary"><span><?= $escaper->escapeHtml(
                            __('Reset My Password')
                        ) ?></span></button>
            </div>
            <div class="secondary ml-4 self-center">
                <a class="action back cursor-pointer"
                   @click ="openForgot = false,openLogin = true,
                   openButtonLogin = <?php echo(json_encode($checkButtonLogin)); ?>"
                >
                    <span class="text-size14 font-medium text-black">
                        <?= $escaper->escapeHtml(__('Back')) ?>
                    </span>
                </a>
            </div>
        </div>
    </form>
</div>


