<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\StoreConfig;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

$storeConfig = $viewModels->require(StoreConfig::class);
$maxItemsToDisplay = $storeConfig->getStoreConfig('checkout/sidebar/max_items_display_count');

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<script>
   /*  var MINI_CART_SUMMARY_COUNT = 0;
    var MINI_CART_INTERVAL = setInterval(function(){
        console.log('minicart reload ='+MINI_CART_SUMMARY_COUNT);
        if (document.querySelector(".minicart_icon_count").textContent ) {
            MINI_CART_SUMMARY_COUNT = parseInt(document.querySelector(".minicart_icon_count").textContent);
            console.log('minicart reload finish='+MINI_CART_SUMMARY_COUNT);
            clearInterval(MINI_CART_INTERVAL);
        }
    }, 300);  */

    function initCartDrawer() {
        return {
            open: false,
            isLoading: false,
            cart: {},
            maxItemsToDisplay: <?= (int) $maxItemsToDisplay ?>,
            itemsCount: 0,
            totalCartAmount: 0,
            getData(data) {
                if (data.cart) {
                    this.cart = data.cart;
                    this.itemsCount = data.cart.items && data.cart.items.length || 0;
                    this.totalCartAmount = this.cart.summary_count; 
                    //this.cart.summary_count = this.itemsCount;
                    this.setCartItems();
                } 
                this.isLoading = false;
            },
            cartItems: [],
            getItemCountTitle() {
                return hyva.strf('(%0 <?= $escaper->escapeJs(__('of')) ?> %1)', this.maxItemsToDisplay, this.totalCartAmount)
            },
            setCartItems() {
                this.cartItems = this.cart.items && this.cart.items.sort((a, b) => b.item_id - a.item_id) || [];

                if (this.maxItemsToDisplay > 0) {
                    this.cartItems = this.cartItems.slice(0, parseInt(this.maxItemsToDisplay, 10));
                }
			   if(document.getElementById('product-addtocart-button-fake')) {
				   var addtocart = document.getElementById('product-addtocart-button-fake');
					addtocart.addEventListener('click', () => { 
						setTimeout(() => {
							this.openCartDrawer();
						}, 2500); 
					});
				
			   }
				
				if(document.querySelectorAll('.btn_cart')) {
					var addtocartnew = document.querySelectorAll('.btn_cart');

					addtocartnew.forEach(addtocartnew => {
					  addtocartnew.addEventListener('click', () => {
						setTimeout(() => {
							this.openCartDrawer();
						}, 2500); 
					  });
					});
				}
				if(document.getElementById('product-addtocart-button')) {
					var addtocartnew2 = document.getElementById('product-addtocart-button');
					
					addtocartnew2.addEventListener('click', () => {
						setTimeout(() => {
							this.openCartDrawer();
						}, 2500); 
					});
				}

               
            },
            deleteItemFromCart(itemId) {
                this.isLoading = true;

                const formKey = hyva.getFormKey();
                const postUrl = BASE_URL + 'checkout/sidebar/removeItem/';

                fetch(postUrl, {
                    "headers": {
                        "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    },
                    "body": "form_key=" + formKey + "&item_id=" + itemId,
                    "method": "POST",
                    "mode": "cors",
                    "credentials": "include"
                }).then(response => {
                    if (response.redirected) {
                        window.location.href = response.url;
                    } else if (response.ok) {
                        return response.json();
                    } else {
                        window.dispatchMessages && window.dispatchMessages([{
                            type: 'warning',
                            text: '<?= $escaper->escapeJs(__('Could not remove item from quote.')) ?>'
                        }]);
                        this.isLoading = false;
                    }
                }).then(result => {
                    window.dispatchMessages && window.dispatchMessages([{
                        type: result.success ? 'success' : 'error',
                        text: result.success
                            ? '<?= $escaper->escapeJs(__('You removed the item.')) ?>'
                            : result.error_message
                    }], result.success ? 5000 : 0)
                    window.dispatchEvent(new CustomEvent('reload-customer-section-data'));
                });
            },
            toggleCartDrawer(event) {
                if (event.detail && event.detail.isOpen !== undefined) {
                    if (event.detail.isOpen) {
                        this.openCartDrawer()
                    } else {
                        this.open = false
                        this.$refs && this.$refs.cartDialogContent && hyva.releaseFocus(this.$refs.cartDialogContent)
                    }
                } else {
                    <?php
                    /*
                     * The toggle-cart event was previously dispatched without parameter to open the drawer (not toggle).
                     * Keeping this in here for backwards compatibility.
                     */
                    ?>
                    this.openCartDrawer()
                }
            },
            openCartDrawer() {
                this.open = true;
                this.$nextTick(() => {
                    this.$refs && this.$refs.cartDialogContent && hyva.trapFocus(this.$refs.cartDialogContent)
                })
            },
            closeCartDrawer() {
                this.$dispatch('toggle-cart', { isOpen: false })
            }
        }
    }
</script>
<section x-cloak
         x-show="cart"
         id="cart-drawer"
         x-data="initCartDrawer()"
         @private-content-loaded.window="getData($event.detail.data)"
         @toggle-cart.window="toggleCartDrawer($event)"
         @keydown.window.escape="closeCartDrawer"
>
        <div role="dialog"
             aria-labelledby="cart-drawer-title"
             aria-modal="true"
             @click.outside="open=false"
             class="fixed inset-y-0 right-0 z-30 flex max-w-full">
            <div class="backdrop"
                 x-show="open"
                 x-transition:enter="ease-in-out duration-500"
                 x-transition:enter-start="opacity-0"
                 x-transition:enter-end="opacity-100"
                 x-transition:leave="ease-in-out duration-500"
                 x-transition:leave-start="opacity-100"
                 x-transition:leave-end="opacity-0"
             role="button"
             @click="closeCartDrawer"
             aria-label="<?= $escaper->escapeHtmlAttr(__('Close minicart')) ?>"></div>
            <div class="relative w-screen max-w-md shadow-2xl"
                 x-show="open"
                 x-transition:enter="transform transition ease-in-out duration-500 sm:duration-700"
                 x-transition:enter-start="translate-x-full"
                 x-transition:enter-end="translate-x-0"
                 x-transition:leave="transform transition ease-in-out duration-500 sm:duration-700"
                 x-transition:leave-start="translate-x-0"
                 x-transition:leave-end="translate-x-full"
            >
                <div
                    x-show="open"
                    x-transition:enter="ease-in-out duration-500"
                    x-transition:enter-start="opacity-0"
                    x-transition:enter-end="opacity-100"
                    x-transition:leave="ease-in-out duration-500"
                    x-transition:leave-start="opacity-100"
                    x-transition:leave-end="opacity-0" class="absolute top-0 right-0 flex pr-6 pt-19">
                    <button @click="open=false" aria-label="Close panel"
                            class="p-0 text-black transition duration-150 ease-in-out hover:text-black">
                        <?= $heroicons->xHtml(); ?>
                    </button>
                </div>
                <div class="flex flex-col h-full bg-lightblue">
                    <?= $block->getChildHtml('cart-drawer.top'); ?>

                    <header class="px-4 pt-19 pb-6">
                        <h2 id="cart-drawer-title" class="text-size18 font-medium text-black">
                        <template x-if="!itemsCount">
                            <div><?= $escaper->escapeHtml(__('My Cart')) ?></div></template>
<template x-if="itemsCount">
                            <div class="minicart-item-count"><span x-html="totalCartAmount"></span> <span x-show="totalCartAmount > 1">items</span><span x-show="totalCartAmount == 1">item</span> in cart</div>
</template>
                            <span class="items-total text-xs text-black"
                                  x-show="maxItemsToDisplay && maxItemsToDisplay < itemsCount"
                                  x-text="getItemCountTitle()">
                            </span>
                        </h2>
                    </header>

                    <?= $block->getChildHtml('cart-drawer.items.before'); ?>

<template x-if="!itemsCount">
                    <div class="relative px-4 py-6 border-bs sm:px-6 border-container">
                        <?= $escaper->escapeHtml(__('Cart is empty')) ?>
                    </div>
                </template>
                    <div class="relative grid overflow-y-auto overflow-x-hidden bg-lightblue cart-items">
                        <template x-for="item in cartItems">
                            <div class="flex items-start cart-item px-4 pt-5 pb-6 transition duration-150
                                ease-in-out">
                                <template x-if="item.product_has_url == 1">
                                    <a :href="item.configure_url" class="w-1/4 pr-6 image">
                                        <img
                                            :src="item.product_image.src"
                                            :width="item.product_image.width"
                                            :height="item.product_image.height"
                                            loading="lazy"
                                        />
                                    </a>
                                </template>
                                <template x-if="!item.product_has_url">
                                    <a :href="item.product_url" class="w-1/4 pr-6 image">
                                        <img
                                            :src="item.product_image.src"
                                            :width="item.product_image.width"
                                            :height="item.product_image.height"
                                            loading="lazy"
                                        />
                                    </a>
                                </template>
                                <div class="w-3/4">
                                    <div>
                                        <template x-if="item.product_has_url == 1">
                                            <a :href="item.configure_url" class="prosku">
                                                <p><span class="product-title text-size16 font-semibold text-darkblack" x-html="item.product_name"></span></p>
                                            </a>
                                        </template>
                                        <template x-if="!item.product_has_url">
                                            <a :href="item.product_url" class="prosku">
                                                <p><span class="product-title text-size16 font-semibold text-darkblack" x-html="item.product_name"></span></p>
                                            </a>
                                        </template>
                                    </div>
                                    <template x-for="option in item.options">
                                        <div class="flex pt-2 pb-1 item-options w-full"  x-show="option.label !== '' && option.label !== 'Weight'">
                                            <div class="flex w-full">
                                                <p class="text-size14 font-medium text-black" x-text="option.label + ':'"></p>
                                                <template x-if="item.product_has_url == 1">
                                                    <a :href="item.configure_url"
                                                    x-show="item.product_type !== 'grouped'"
                                                    class="inline-flex"><p class="pl-1 text-size14 font-normal text-black" x-html="option.value"></p></a>
                                                </template>
                                                <template x-if="!item.product_has_url">
                                                    <a :href="item.product_url"
                                                    x-show="item.product_type !== 'grouped'"
                                                    class="inline-flex"><p class="pl-1 text-size14 font-normal text-black" x-html="option.value"></p></a>
                                                </template>
                                            </div>
                                        </div>
                                    </template>
                                    <p class="pb-4 pt-1"><span x-html="item.product_price" class="text-size20 font-bold text-custom-blue pricebox"></span></p>
                                    <div class="text-xl flex qty-fields items-center">
                                        <p><span class="qty text-size14 font-semibold text-darkblack mr-1">QTY</span><span x-html="item.qty" class="qty-label text-center text-size16 font-semibold text-darkblack inline-block"></span></p>
                                        <div class="ml-auto">
                                            <?php /*<a :href="item.configure_url"
                                               x-show="item.product_type !== 'grouped'"
                                               class="inline-flex p-2 mr-2 btn btn-primary">
                                                <?= $heroicons->pencilHtml('', 20, 20); ?>
                                            </a>*/?>
                                            <button 
                                                    @click="deleteItemFromCart(item.item_id)"
                                            >
                                                <img src="<?php echo $this->getViewFileUrl('images/Delete.png'); ?>" alt="Delete" width="12" height="16">
                                            </button>
                                        </div>
                                    </div>                                   

                                </div>
                            </div>
                        </template>
                    </div>
<template x-if="itemsCount">
                    <?= $block->getChildHtml('cart-drawer.totals.before'); ?>

                    <div class="relative bg-lightblue grid pt-3 pb-4">
                        <div class="w-full transition duration-150 ease-in-out sub-total">
                            <p class="text-darkgray text-size16 font-normal flex items-center pb-2"><?= $escaper->escapeHtml(__('Subtotal')) ?>: <span x-html="cart.subtotal" class="font-bold text-size22 text-custom-blue"></span></p>
                        </div>
                        <div class="w-full transition duration-150 ease-in-out
                            chekout-btn">
                            <?php /*<a @click.prevent.stop="$dispatch('toggle-authentication',
                                {url: '<?= $escaper->escapeUrl($block->getUrl('checkout')) ?>'});"
                               href="<?= $escaper->escapeUrl($block->getUrl('checkout')) ?>"
                               class="inline-flex btn btn-primary">
                                <?= $escaper->escapeHtml(__('Checkout')) ?>
                            </a>
                            <span><?= $escaper->escapeHtml(__('or')) ?></span> */?>
                            <a href="<?= $escaper->escapeUrl($block->getUrl('checkout/cart')) ?>"
                               class="no-underline block relative font-medium text-size16 text-custom-white bg-custom-blue">
                                <?= $escaper->escapeHtml(__('Proceed to Cart')) ?>
                            </a>
                        </div>
                        <?= $block->getChildHtml('extra_actions') ?>
                    </div>
</template>
                    <?= $block->getChildHtml('cart-drawer.bottom'); ?>
                </div>
            </div>
            <?= $block->getChildHtml('loading') ?>
        </div>
    </template>
</section>