<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\ProductList\Toolbar;
use Magento\Framework\Escaper;

/** @var Toolbar $block */
/** @var Escaper $escaper */
?>
<?php if ($block->isEnabledViewSwitcher()): ?>

    <?php $modes = $block->getModes(); ?>
    <?php if ($modes && count($modes) > 1): ?>
        <div class="modes flex space-x-1 mr-2 items-center px-2 py-2 order-3">
            <strong class="modes-label sr-only"><?= $escaper->escapeHtml((string)__('View as')) ?></strong>
            <?php foreach ($block->getModes() as $code => $label): ?>
                <?php if ($block->isModeActive($code)): ?>
                    <strong title="<?= $escaper->escapeHtmlAttr($label) ?>"
                            class="modes-mode active mode-<?= $escaper->escapeHtmlAttr(strtolower($code)) ?>"
                            data-value="<?= $escaper->escapeHtmlAttr(strtolower($code)) ?>">
                        <span><?= $escaper->escapeHtml($label) ?> view</span>
                    </strong>
                <?php else: ?>
                    <a class="modes-mode mode-<?= $escaper->escapeHtmlAttr(strtolower($code)) ?>
                        opacity-60 hover:opacity-100"
                       title="<?= $escaper->escapeHtmlAttr($label) ?>"
                       href="#"
                       @click.prevent="changeUrl(
                        'product_list_mode', '<?= $escaper->escapeHtmlAttr(strtolower($code)) ?>', options.modeDefault
                       )"
                       data-role="mode-switcher"
                       data-value="<?= $escaper->escapeHtmlAttr(strtolower($code)) ?>"
                       aria-label="<?= $escaper->escapeHtmlAttr($label) ?>">
                        <span><?= $escaper->escapeHtml($label) ?> view</span>
                    </a>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>

    <?php else: ?>
        <div class="modes w-20 order-1 col-span-1 sm:col-span-2 md:col-span-1 lg:col-span-2"></div>
    <?php endif; ?>

<?php endif; ?>

<?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>


