<?php
/** @var \Magento\DataServices\Block\Context $block */
?>

<script>
    window.addEventListener('load', function () {
        magentoStorefrontEvents.context.setPage({
            pageType: "<?= /* @noEscape */ $block->getData('page_type'); ?>"
        });
        magentoStorefrontEvents.context.setContext("pageExtended", {
            action: "<?= /* @noEscape */ $block->getData('step_name'); ?>"
        });

        <?php //cartId is set inside Hyva_MagentoDataServices::set-cart-context.phtml ?>
    });
    window.addEventListener('shoppingCartContextSet', function () {
        magentoStorefrontEvents.publish.shoppingCartView();
    });
</script>

