<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
/** @var \Magento\DataServices\Block\Context $block */
?>

<script>
  //  require(['magentoStorefrontEvents'], function (magentoStorefrontEvents) {
    window.addEventListener('load', function () {
        if(!magentoStorefrontEvents) return;

        magentoStorefrontEvents.context.setPage({
            pageType: "<?= /* @noEscape */ $block->getData('page_type'); ?>"
        });
        magentoStorefrontEvents.context.setContext("pageExtended", {
            action: "<?= /* @noEscape */ $block->getData('step_name'); ?>"
        });
    });
</script>
