<?php
/** @var \Magento\DataServices\Block\Context $block */
?>

<script>
    window.addEventListener('load', function () {
        window.magentoStorefrontEvents = magentoStorefrontEvents;
        magentoStorefrontEvents.context.setStorefrontInstance(
            <?= /* @noEscape */ $block->getStorefrontInstanceContext(); ?>
        );
        magentoStorefrontEvents.context.setMagentoExtension({
            magentoExtensionVersion: "<?= /* @noEscape */ $block->getExtensionVersion(); ?>",
        });
        magentoStorefrontEvents.context.setDataServicesExtension({
            version: "<?= /* @noEscape */ $block->getExtensionVersion(); ?>",
        });
        magentoStorefrontEvents.context.setPage({
            pageType: "<?= /* @noEscape */ $block->getData('page_type'); ?>"
        });
        magentoStorefrontEvents.context.setContext("pageExtended", {
            action: "<?= /* @noEscape */ $block->getData('step_name'); ?>"
        });

        magentoStorefrontEvents.publish.pageView();
    });
</script>
