<?php
/** @var \Magento\DataServices\Block\Context $block */
/** @var \Magento\DataServices\ViewModel\WishListProvider $viewModel */
$viewModel = $block->getViewModel();
$userAction = $viewModel->getUserAction();
$pageAction = $userAction ?: $block->getData('step_name');
?>

<script>
    window.addEventListener('load', function () {
        magentoStorefrontEvents.context.setPage({
            pageType: "<?= /* @noEscape */ $block->getData('page_type'); ?>"
        });
        magentoStorefrontEvents.context.setContext("pageExtended", {
            action: "<?= /* @noEscape */ $block->getData('step_name'); ?>"
        });
        magentoStorefrontEvents.context.setShoppingCart({
            id: <?= /* @noEscape */ $block->getCartId(); ?>
        });
    });
</script>
