<?php
/**  @var $block \Amasty\RequestQuote\Block\Cart\Grid */
?>
<?php $mergedCells = ($block->getTaxHelper()->displayCartBothPrices() ? 2 : 1); ?>
<?= $block->getChildHtml('form_before') ?>
<div x-data="cartQuoteTotals()"
     class="relative flex-auto w-4/6 mt-2 float-left lg:order-1 lg:pr-8 quote-amstyleft"
>
<form action="<?= $escaper->escapeUrl($block->getUrl('amasty_quote/cart/updatePost')) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'
      class="form form-cart amasty-quote-update"
      enctype="multipart/form-data">
    <?= $block->getBlockHtml('formkey') ?>
    <div class="cart table-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?>">
        <div id="shopping-cart-table"
               class="table-row-items border-b border-container">
             <div class="flex text-size18 font-semibold text-primary-lighter border-gray-1 border-container">
                <div class="p-2 th prodct"><span><?= /* @noEscape */ __('Product') ?></span></div>
                <div class="p-2 text-center th prce"><span><?= /* @noEscape */ __('Price') ?></span></div>
                <div class="p-2 text-center th qutanty"><span><?= /* @noEscape */ __('Quantity') ?></span></div>
                <div class="p-2 text-right th subt"><span><?= /* @noEscape */ __('Subtotal') ?></span></div>
             </div>
            <?php foreach ($block->getItems() as $item): ?>
                <?= $block->getItemHtml($item) ?>
            <?php endforeach ?>
        </div>
    </div>
    <div class="cart main actions flex flex-col mt-5 mb-3 md:flex-row lg:mb-0 mt-4">
        <?php if ($block->getContinueShoppingUrl()): ?>
            <!--<a class="action continue btn btn-primary justify-center mr-4"
               href="<?= $escaper->escapeUrl($block->getContinueShoppingUrl()) ?>"
               title="<?= $escaper->escapeHtml(__('Continue Shopping')) ?>">
                <span><?= /* @noEscape */ __('Continue Shopping') ?></span>
            </a>-->
        <?php endif; ?>
        <!--<button type="submit"
                name="update_cart_action"
                data-cart-empty=""
                value="empty_cart"
                title="<?= $escaper->escapeHtml(__('Clear Quote')) ?>"
                class="action clear-quote btn btn-primary justify-center mr-4" id="empty_cart_button"
                x-on:click="updateQuoteCartData($event, 'empty_cart')">
            <span><?= /* @noEscape */ __('Clear Quote') ?></span>
        </button>
        <button type="submit"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?= $escaper->escapeHtml(__('Update Quote')) ?>"
                class="action update btn btn-primary justify-center mr-4"
                x-on:click="updateQuoteCartData($event, 'update_qty')">
            <span><?= /* @noEscape */ __('Update Quote') ?></span>
        </button>-->
    </div>
</form>
<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after') ?>
</div>