<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) Amasty (https://www.amasty.com)
 * @package FAQ and Product Questions Hyva
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Amasty\Faq\Block\Lists\QuestionsList;
use Amasty\Faq\Block\Rating\Rating;
use Magento\Framework\Escaper;

/** @var QuestionsList $block */
/** @var Rating $rating */
/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
$rating = $block->getChildBlock('amasty_faq_rating');
// phpcs:disable Generic.Files.LineLength.TooLong
?>
<div class="amfaq_questions widget">
    <?php if ($block->hasBlockTitle()): ?>
        <div class="amfaq-title">
            <?= $escaper->escapeHtml((string)$block->getBlockTitle()) ?>
        </div>
    <?php endif ?>
    <?php if ($questions = $block->getQuestions()): ?>
        <?php foreach ($questions as $question): ?>
            <?php $uniqueId = '_' . uniqid() ?>
            <div
                class="amquestion-wrapper border-container border-b mb-4"
                x-data="{selected: null}"
            >
                <button
                        class="amquestion-title text-left text-lg font-light cursor-pointer
                                flex justify-between items-start w-full"
                        :class="{'opened-question': selected === 1}"
                        type="button"
                        @click="selected !== 1 ? selected = 1 : selected = null">
                    <span class="question-text">
                        <?= /** @noEscape */ $block->highlight($escaper->escapeHtml($question->getTitle())) ?>
                    </span>
                    <?= $heroicons->chevronDownHtml('duration-300', 20, 20) ?>
                </button>
                <div
                    class="amquestion-content text-base relative overflow-hidden
                            transition-all max-h-0 duration-300 mb-3"
                    x-ref="container<?= $escaper->escapeHtmlAttr($uniqueId) ?>"
                    x-bind:style="selected == 1 ?
                        'max-height: max-content' : ''"
                >
                    <div class="amfaq-short-answer-container mt-2">
                        <?= /** @noEscape */ $block->highlight($block->getShortAnswer($question)) ?>
                    </div>
                    <div>
                        <?php if (!$question->isShowFullAnswer()): ?>
                            <div>
                                <a
                                    href="<?= $escaper->escapeUrl($block->getQuestionLink($question)) ?>"
                                    class="text-blue-600 hover:underline text-sm"
                                >
                                    <?= $escaper->escapeHtml(__('Read More')) ?>
                                </a>
                            </div>
                        <?php endif ?>

                        <?php /*if ($rating): ?>
                            <div class="mt-4 flex">
                                <?php $rating->ratingItemHtml((int)$question->getQuestionId()) ?>
                                <?=  $rating->toHtml() ?>
                            </div>
                        <?php endif */ ?>
                    </div>
                </div>
            </div>
        <?php endforeach ?>

        <?php if ($pager = $block->getPagerHtml()): ?>
            <div class="amfaq-pager"><?= /** @noEscape */ $pager ?></div>
        <?php endif ?>
    <?php else: ?>
        <div class="am-no-items">
            <?= $escaper->escapeHtml($block->getNoItemsLabel()) ?>
        </div>
    <?php endif ?>
</div>

<?php if ($block->isShowQuestionForm()): ?>
    <?= /** @noEscape */ $block->getChildHtml('amasty_faq_ask_question_form') ?>
<?php endif ?>

<?php if ($block->isAddStructuredData()): ?>
    <?= /** @noEscape */ $block->getQuestionsStructuredDataHtml() ?>
<?php endif ?>

<?= /** @noEscape */ $block->getChildHtml('amasty_faq_product_url') ?>
