<?php
$element = $block->getElement();
$note = $element->getNote() ? '<div class="note">' . $element->getNote() . '</div>' : '';
$elementBeforeLabel = $element->getExtType() == 'checkbox' || $element->getExtType() == 'radio';
$addOn = $element->getBeforeElementHtml() || $element->getAfterElementHtml();
$fieldId = ($element->getHtmlId()) ? ' id="attribute-' . $element->getHtmlId() . '-container"' : '';
$fieldClass = "field field-{$element->getId()} {$element->getCssClass()}";
$fieldClass .= ($elementBeforeLabel) ? ' choice' : '';
$fieldClass .= ($addOn) ? ' with-addon' : '';
$fieldClass .= ($element->getRequired()) ? ' required' : '';
$fieldClass .= ($note) ? ' with-note' : '';

$fieldAttributes = $fieldId . ' class="' . $fieldClass . '" '
    . $block->getUiId('form-field', $element->getId());


$circularDesignerToolBlock = $block->getLayout()
->createBlock(\Dcw\CircularDesignerTool\Block\Adminhtml\CircularDesignerTool\Grid::class);
$circularDesignerToolJsonHelper = $circularDesignerToolBlock->jsonHelper();
?>

<?php $block->checkFieldDisable() ?>
<?php
    $elementToggleCode = $element->getToggleCode() ? $element->getToggleCode()
        : 'toggleValueElements(this, this.parentNode.parentNode.parentNode)';
?>
<?php if (!$element->getNoDisplay()): ?>
    <?php if ($element->getType() == 'hidden'): ?>
        <?= /* @noEscape */ $element->getElementHtml() ?>
    <?php else: ?>
    <div <?= /* @noEscape */ $fieldAttributes ?> data-attribute-code="<?= /* @noEscape */ $element->getHtmlId() ?>"
        data-apply-to="<?= /* @noEscape */ $block->escapeHtml($circularDesignerToolJsonHelper
        ->jsonEncode($element->hasEntityAttribute() ? $element->getEntityAttribute()->getApplyTo() : []))?>"
        >
        <?php if ($elementBeforeLabel): ?>
            <?= /* @noEscape */ $block->getElementHtml() ?>
            <?= /* @noEscape */ $element->getLabelHtml() ?>
            <?= /* @noEscape */ $note ?>
        <?php else: ?>
            <?= /* @noEscape */ $element->getLabelHtml() ?>
            <div class="control">
            <?= ($addOn) ? '<div class="addon">' . $block->getElementHtml() . '</div>' : $block->getElementHtml(); ?>
            <?= /* @noEscape */ $note ?>
            </div>
        <?php endif; ?>
        <div class="field-service" value-scope="<?= /* @noEscape */ $block->getScopeLabel()?>">
            <?php if ($block->canDisplayUseDefault()): ?>
                <label for="<?= /* @noEscape */ $element->getHtmlId() ?>_default" class="choice use-default">
                    <input <?php if ($element->getReadonly()):?> disabled="disabled"<?php endif; ?>
                            type="checkbox"
                            name="use_default[<?= /* @noEscape */ $block->getElementName() ?>]"
                            class="use-default-control"
                            id="<?= /* @noEscape */ $element->getHtmlId() ?>_default"
                            <?php if ($block->usedDefault()): ?>
                                checked="checked" value="true"
                            <?php else: ?>
                                value="false"
                            <?php endif; ?>
                    />
                    <span class="use-default-label">Use Default Value</span>
                </label>
            <?php endif; ?>
        </div>
    </div>
    <?php endif; ?>
<?php endif; ?>