<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var \Magento\Framework\View\Element\Template $block */ ?>
<?php $_shipment = $block->getShipment() ?>
<?php
/* @var \Magento\Sales\Model\Order $_order */
$_order = $block->getOrder() ?>
<?php if ($_shipment && $_order) : ?>
    <?php $trackCollection = $_shipment->getTracksCollection() ?>
    <?php if ($trackCollection) : ?>
        <br />
        <table class="shipment-track" width="auto" align="center" cellpadding="0" cellspacing="0" border="0" style="padding-bottom: 40px;">
            <thead>
            <tr>
                <th style="font-family:'Open Sans',Arial,sans-serif;font-weight:700;font-size:16px;line-height:24px;color:#000000;padding-bottom: 15px;padding-right: 10px;text-align: left;"><?= $block->escapeHtml(__('Shipped By')) ?></th>
                <th style="font-family:'Open Sans',Arial,sans-serif;font-weight:700;font-size:16px;line-height:24px;color:#000000;padding-bottom: 15px;padding-right: 10px;text-align: left;"><?= $block->escapeHtml(__('Tracking Number')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($trackCollection as $_item) : ?>
                <tr>
                    <td style="text-align: left;text-transform: capitalize;font-family:'Open Sans',Arial,sans-serif;font-weight:400;font-size:14px;line-height:20px;color:#000000;margin:0 0 0px 0;padding-bottom: 10px;padding-right: 10px;"><?= $block->escapeHtml($_item->getTitle()) ?>:</td>
                    <td style="text-align: left;font-family:'Open Sans',Arial,sans-serif;font-weight:400;font-size:14px;line-height:20px;color:#296497;margin:0 0 0px 0;padding-bottom: 10px;padding-right: 10px;">
                        <a style="color:#296497;text-decoration: underline;font-weight: 600;" href="<?= $block->escapeUrl($block->getTrackingUrl()->getUrl($_item)) ?>" target="_blank">
                            <?= $block->escapeHtml($_item->getNumber()) ?>
                        </a>
                    </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    <?php endif; ?>
<?php endif; ?>
