<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\AmastyRequestQuote\ViewModel\Cart\Items;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

$productId = $block->getProductId();
$buttonTitle = __('Update Quote');
$quoteCartViewModel = $viewModels->require(Items::class)
?>
<?php echo $block->getChildHtml('cart_quote_js'); ?>
<div x-data="cartQuoteTotals()">
    <button x-on:click="updateQuote($event)" type="submit" form="product_addtocart_form" title="Add to Cart" class="btn btn-primary inline-block mb-4 sm:mr-6" id="product-addtocart-button-fake">
        <span><?= $buttonTitle ?></span>
    </button>
</div>
