<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Hyva_BssSocialLogin
 * @author     Extension Team
 * @copyright  Copyright (c) 2022 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

use Bss\SocialLogin\Block\SocialLogin\EnableModule;

/** @var EnableModule $block */

if (!$block->isEnable()) {
    return;
}
?>
<script>
    function initSocialLoginPost() {
        return {
            submitForm(form) {
                event.preventDefault();
                var loginRefererElement = document.getElementById("sociallogin-login-referer");
                var value = loginRefererElement.value;
                fetch(form.action, {
                    headers: {
                        contentType: "application/json;charset=utf-8",
                    },
                    body: new URLSearchParams({
                        form_key: hyva.getFormKey(),
                        'refress-redirect-url':value
                    }),
                    method: "POST",
                    mode: "cors",
                    credentials: "include",
                }).then(response => {
                    if (response.redirected) {
                        window.location.href = response.url;
                    } else {
                        window.dispatchMessages("warning", "Post request failed", 5000);
                    }
                })
            }
        }
    }
</script>
<form style="display:none;" class="form" x-data="initSocialLoginPost()" @submit="submitForm($el)"
      action="<?= $block->escapeUrl($block->getUrl('sociallogin/account/loginPost')); ?>"
      method="post"
      id="sociallogin-login-form"
>
    <input id="sociallogin-login-referer" name="refress-redirect-url" type="hidden" value="" />
    <input id="sociallogin-login-submit" type="submit" value="sociallogin" style="font-size:0"/>
</form>
