<?php
if ($block->showInstagramproImages()):
    ?>
<div class="instagrampro-view clearer">
    <div class="heading_instagram">Instagram Feed</div>
    <?php
    $count = 0;
    $linkurl = "javascript:void(0);"; ?>
    <div id="">
        <div id="thumbnail-slider">
            <div class="inner">
                <div class="outer w-full instagram_feed owl-carousel owl-theme">
                    <?php
                    foreach ($block->getInstagramproGalleryImages() as $_image):
                        $count++;
                        $id = $_image['image_id'];
                        $imagetitle = $_image['image_title'];

                        ?>
                        <div class="instagram-slider-li item">
                            <div id="mainimgdiv">
                                <?php if ($_image['media_type'] == "carousel_album" || $_image['media_type'] == "image") { ?>
                                <?php $curl = curl_init($_image['thumbnail_url']);
                                curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
                                curl_setopt($curl, CURLOPT_HEADER, true);
                                curl_setopt($curl, CURLOPT_NOBODY, true);
                                curl_exec($curl);
                                $content_type = curl_getinfo($curl, CURLINFO_CONTENT_TYPE);
                                curl_close($curl);
                                if (strpos($content_type, "image/") === 0) { ?>
                                <a href="<?php echo $linkurl; ?>" target="_blank">
                                        <img class="thumb" src="<?php echo $_image['thumbnail_url']; ?>" alt="Image"
                                             title="<?php echo $imagetitle; ?>"
                                             onmouseover="showinstadesc(<?php echo $count ?>);"
                                             onmouseout="hideinstadesc(<?php echo $count ?>);"/>
                                    </a>
                               <?php  } else { ?>
                                <img src="<?php echo $block->getViewFileUrl('images/placeholder.png'); ?>" alt="Placeholder image" title="<?php echo $imagetitle; ?>"
                                             onmouseover="showinstadesc(<?php echo $count ?>);"
                                             onmouseout="hideinstadesc(<?php echo $count ?>);"/>
                                <?php } ?>
                                <?php  } else {?>
                                    <a href="<?php echo $linkurl; ?>" target="_blank">
                                        <video class="thumb" width="100%" controls onmouseover="showinstadesc(<?php echo $count ?>);"
                                               onmouseout="hideinstadesc(<?php echo $count ?>);">
                                            <source src="<?php echo $_image['thumbnail_url']; ?>" type="video/mp4">
                                            Your browser does not support the video tag.
                                        </video>
                                    </a>
                                <?php } ?>
                                    <div class="hoverp <?php echo "newhover" . $count; ?>"
                                         id="<?php echo "phover" . $count ?>"
                                         onmouseover="showinstadesc(<?php echo $count ?>);"
                                         onmouseout="hideinstadesc(<?php echo $count ?>);"
                                         onclick="javascript:showpopupaction('<?php echo $id ?>',<?php echo $count ?>);">
                                        <div id="innerdiv">
                                            <?php  if (!empty($_image['image_desc'])) { ?>
                                                <div class="hover-description">
                                                    <?php
                                                    if (strlen($_image['image_desc']) > 250) {
                                                        echo __(substr($_image['image_desc'], 0, 250) . "...");
                                                    } else {
                                                        echo __(substr($_image['image_desc'], 0, 250));
                                                    }
                                                    ?>
                                                </div>
                                            <?php }?>
                                            <span class="imagelikes flex items-center"><img class="mr-1" src="<?php echo $this->getViewFileUrl('images/insta-icon2.svg'); ?>" alt="InstaComments"><span class="text-size14 font-normal text-white"><?php echo $_image['image_likes']; ?></span></span>
                                            <span class="imagecomments flex items-center"><img class="mr-1" src="<?php echo $this->getViewFileUrl('images/insta-icon1.svg'); ?>" alt="InstaLikes"><span class="text-size14 font-normal text-white"><?php echo $_image['image_comments']; ?></span></span>
                                        </div>
                                    </div>
                                    <input type="hidden" name="<?php echo 'curimageid' . $count; ?>"
                                           id="<?php echo 'curimageid' . $count; ?>" value="<?php echo $id ?>"/>
                            </div>
                        </div>
                    <?php endforeach; ?>

                </div>
            </div>
        </div>
    </div>
    <input type="hidden" name="curimage" id="curimage" value="0"/>

    <div id="popupdiv">
        <div id="backgrounddiv">
            <div id="loadingdiv"></div>
            <div id="whitebgdiv"></div>
        </div>
    </div>
    <script>
        jQuery(function(){
            jQuery('.instagram_feed').owlCarousel({
                loop: false,
                margin: 25,
                responsiveClass: true,
                nav:true,
                dots:false,
                responsive:{
                    0:{
                        items:2,
                        margin:12
                    },
                    767:{
                        items:2,
                        margin:12
                    },
                    1024:{
                        items:3
                    },
                    1025:{
                        items:4
                    },
                    1360:{
                        items:5
                    }
                }
            });
        });

        function showinstadesc(Id) {
            jQuery(".newhover" + Id).addClass('instagramproshow');
        }

        function hideinstadesc(Id) {
            jQuery(".newhover" + Id).removeClass('instagramproshow');
        }

        function closepopup() {
            jQuery('#backgrounddiv').css('display', 'none');
            jQuery('#loadingdiv').css('display', 'none');
            jQuery('#whitebgdiv').css('display', 'none');

        }

        function showpopupaction(ImgId, ImgNum) {

            jQuery('#curimage').val(ImgNum);
            var formurl = '<?php echo $block->getPopupUrl(); ?>';
            jQuery.ajax({
                type: "POST",
                url: formurl,
                data: {Id: ImgId},
                beforeSend: function () {
                    jQuery('#whitebgdiv').css('display', 'none');
                    jQuery('#backgrounddiv').css('display', 'block');
                    jQuery('#loadingdiv').css('display', 'block');
                },
                success: function (transport) {
                    var response = transport || "no response text";

                    jQuery('#backgrounddiv').html(response.output);

                    //effact on popup js code
                    jQuery('.alltitleul > li').hover(function (e) {

                        var classname = jQuery(this).attr('class');
                        var xy = classname.split('-');
                        <?php if ($block->showProductInPopup()): ?>
                        jQuery('#titletext').html(jQuery(this).find('div').html());
                        <?php else: ?>
                        jQuery('#titletext').html(jQuery(this).html());
                        <?php endif; ?>
                        var instagram_img_width = jQuery('.instagrampro-view #popupdiv #leftpart img').width();
                        var instagram_img_height = jQuery('.instagrampro-view #popupdiv #leftpart img').height();
                        console.log(instagram_img_width +' | '+instagram_img_height);

                        var adjust_x = Math.ceil((parseInt(instagram_img_height)*19)/525);
                       // var adjust_y = Math.ceil((parseInt(instagram_img_width)*2)/525);

                        var x_top = Math.ceil((parseInt(instagram_img_height)*(parseFloat(xy[0]) - adjust_x ))/525);
                        var y_left = Math.ceil((parseInt(instagram_img_width)*parseFloat(xy[1]))/525);

                        console.log(x_top +' ||| '+y_left);

                        jQuery('#titletext').css('top', (x_top ) + 'px');

                        if(jQuery(window).width() > 767 ){
                            jQuery('#titletext').css('top', (x_top ) + 'px');
                            jQuery('#titletext').css('left', (y_left ) + 'px');
                        }else{
                            jQuery('#titletext').css('top', (x_top -25 ) + 'px');
                            jQuery('#titletext').css('left', (y_left ) + 'px');
                            
                        }
                    });

                    jQuery('.alltitleul > li').mouseleave(function (e) {
                        jQuery('#titletext').html('');
                    });
                    slideIndex = 1;
                    showDivs(slideIndex);
                },
                error: function () {
                    alert('Something went wrong...');
                }
            });
        }

        function prevnextpopup(Acn) {
            //Acn 1=Prev 2=Next
            var curimg = parseInt(jQuery('#curimage').val());
            if (Acn == 1)// Prev
            {
                curimg = curimg - 1;
                if (curimg <= 0) {
                    curimg = <?php echo $count ?>;
                }

            } else // Next
            {
                curimg = curimg + 1;
                if (curimg > <?php echo $count ?>) {
                    curimg = 1;
                }
            }

            var ImgId = jQuery('#curimageid' + curimg).val();
            showpopupaction(ImgId, curimg);
        }

        var slideIndex = 1;

        function plusDivs(n) {
            showDivs(slideIndex += n);
        }

        function showDivs(n) {
            var i;
            var x = document.getElementsByClassName("mySlides");
            if (n > x.length) {
                slideIndex = 1
            }
            if (n < 1) {
                slideIndex = x.length
            }
            ;
            for (i = 0; i < x.length; i++) {
                x[i].style.display = "none";
            }

            if (x.length > 0) {
                x[slideIndex - 1].style.display = "block";
            }

            if (slideIndex == 1) {
                jQuery("#titletext").show();
            }
            else {
                jQuery("#titletext").hide();
            }
        }
        function changeprodtoleft(prodId) {
            jQuery(".insta-popup-product-view-left-img img").css('opacity', '0.4');
            jQuery("#popprdloadingdiv").css('display', 'block');
            var formurl = '<?php echo $block->getPopupChangeProductUrl(); ?>';
            jQuery.ajax({
                type: "GET",
                url: formurl,
                data: {id: prodId},
                dataType: "json",
                showLoader: true,
                async: false,
                success: function (transport) {
                    jQuery("#popprdloadingdiv").css('display', 'none');
                    jQuery(".insta-popup-product-view-left-img img").css('opacity', '1');
                    var response = transport || "no response text";
                    jQuery(".insta-popup-product-view-left-img img").attr('src', response['prodimg']);
                    jQuery(".insta-popup-product-view-left-img a").attr('href', response['produrl']);
                    jQuery(".popup-img-desc .instatitle").text(response['prodname']);
                    jQuery(".popup-img-desc .popup-img-desc-part").text(response['proddesc']);

                    jQuery(".fb-share-link").attr("href", "https://www.facebook.com/sharer/sharer.php?u=" + response["produrl"] + "&t=" + response["prodname"]);
                    jQuery(".tiwtter-share-link").attr("href", "https://twitter.com/share?url=" + response['produrl'] + "&text=" + response['prodname']);
                    jQuery(".linkedin-share-link").attr("href", "https://www.linkedin.com/shareArticle?mini=true&url=" + response['produrl'] + "&title=" + response['prodname']);


                },
                error: function () {
                    jQuery("#popprdloadingdiv").css('display', 'none');
                    jQuery(".insta-popup-product-view-left-img img").css('opacity', '1');
                    alert('Something went wrong...');
                }
            });
        }


    </script>

    <?php endif; ?>
