<?php if ($block->Isshowindetailsection()): ?>
    <div class="instagrampro-view clearer">
    <h3><?php echo __('Instagram Feed') ?></h3>
    <?php
    $count = 0;
    $linkurl = "javascript:void(0);"; ?>

    <div id="thumbnail-slider">
        <div class="inner">
            <div class="owl-carousel owl-theme">
                <?php
                foreach ($block->getInstagramproGalleryImages() as $_image):
                    $count++;
                    $id = $_image['image_id'];
                    $imagetitle = $_image['image_title'];
                    ?>
                    <div class="instagram-slider-li item">

                        <div id="mainimgdiv">
                            <?php if ($_image->getMediaType() == "video"){?>
                            <a href="<?php echo $linkurl; ?>" target="_blank">
                                <video width="100%" controls onmouseover="showinstadesc(<?php echo $count ?>);"
                                       onmouseout="hideinstadesc(<?php echo $count ?>);" style="height: 203px; border-radius: 25px;">
                                    <source src="<?php echo $_image->getThumbnailUrl(); ?>" type="video/mp4">
                                    Your browser does not support the video tag.
                                </video>
                            </a>
                            <?php } else { ?>
                            <a href="<?php echo $linkurl; ?>" target="_blank">
                                <img class="thumb" src="<?php echo $_image['thumbnail_url']; ?>" alt="Image" title="<?php echo $imagetitle; ?>" onmouseover="showinstadesc(<?php echo $count ?>);" onmouseout="hideinstadesc(<?php echo $count ?>)"/>
                            </a>
                            <?php  } ?>
                            <div class="hoverp <?php echo "producthover".$count; ?>" id="<?php echo "phover".$count?>" onmouseover="showinstadesc(<?php echo $count ?>);" onmouseout="hideinstadesc(<?php echo $count ?>);" onclick="javascript:showpopupaction('<?php echo $id?>',<?php echo $count?>);">
                                <div id="innerdiv">
                                    <span class="imagelikes"><i class="fa fa-heart" aria-hidden="true"></i><?php echo $_image['image_likes']; ?></span>
                                    <span class="imagecomments"><i class="fa fa-comments-o" aria-hidden="true"></i><?php echo $_image['image_comments']; ?></span>
                                </div>
                            </div>
                            <input type="hidden" name="<?php echo 'curimageid'.$count; ?>" id="<?php echo 'curimageid'.$count;?>" value="<?php echo $id?>" />
                        </div>
                    </div>
                <?php endforeach; ?>

            </div>
        </div>
    </div>
    <input type="hidden" name="curimage" id="curimage" value="0"/>
    <div id="popupdiv">
        <div id="backgrounddiv">
            <div id="loadingdiv"></div>
            <div id="whitebgdiv"></div>
        </div>
    </div>
    <script type="text/javascript">
        require(['jquery','Magecomp_Instagrampro/js/owl.carousel'], function($)
        {
            jQuery('.owl-carousel').owlCarousel({
                loop: true,
                margin: 10,
                responsiveClass: true,
                stopOnHover : true,
                responsive: {
                    0: {
                        items: 1,
                        nav: true
                    },
                    600: {
                        items: 3,
                        nav: false
                    },
                    1000: {
                        items: 5,
                        loop: true,
                        margin: 20
                    }
                }
            });
        });
        function showinstadesc(Id)
        {
            jQuery(".producthover"+Id).addClass('instagramproshow');
        }

        function hideinstadesc(Id)
        {
            jQuery(".producthover"+Id).removeClass('instagramproshow');
        }

        function closepopup()
        {
            jQuery('#backgrounddiv').css('display','none');
            jQuery('#loadingdiv').css('display','none');
            jQuery('#whitebgdiv').css('display','none');

        }

        function showpopupaction(ImgId,ImgNum)
        {
            jQuery('#curimage').val(ImgNum);
            var formurl = '<?php echo $block->getProductPopupUrl(); ?>';
            jQuery.ajax({
                type: "POST",
                url: formurl,
                data: {Id: ImgId},
                beforeSend: function()
                {
                    jQuery('#whitebgdiv').css('display','none');
                    jQuery('#backgrounddiv').css('display','block');
                    jQuery('#loadingdiv').css('display','block');
                },
                success: function(transport)
                {
                    var response = transport || "no response text";
                    jQuery('#backgrounddiv').html(response);
                    //effact on popup js code
                    jQuery('.alltitleul > li').hover(function (e){

                        var classname = jQuery(this).attr('class');
                        var xy = classname.split('-');
                        <?php if ($block->showProductInPopup()): ?>
                        jQuery('#titletext').html(jQuery(this).find('div').html());
                        <?php else: ?>
                        jQuery('#titletext').html(jQuery(this).html());
                        <?php endif; ?>
                        jQuery('#titletext').css('top',xy[0]+'px');
                        jQuery('#titletext').css('left',xy[1]+'px');
                    });
                    jQuery('.alltitleul > li').mouseleave(function (e){
                        jQuery('#titletext').html('');
                    });
                    slideIndex = 1;
                    showDivs(slideIndex);
                },
                error: function()
                {
                    alert('Something went wrong...');
                }
            });
        }

        function prevnextpopup(Acn)
        {
            //Acn 1=Prev 2=Next
            var curimg = parseInt(jQuery('#curimage').val());
            if(Acn == 1)// Prev
            {
                curimg = curimg - 1;
                if(curimg <= 0)
                {
                    curimg = <?php echo $count ?>;
                }

            } else // Next
            {
                curimg = curimg + 1;
                if(curimg > <?php echo $count ?>)
                {
                    curimg = 1;
                }
            }

            var ImgId = jQuery('#curimageid'+curimg).val();
            showpopupaction(ImgId,curimg);
        }

        var slideIndex = 1;

        function plusDivs(n)
        {
            showDivs(slideIndex += n);
        }

        function showDivs(n)
        {
            var i;
            var x = document.getElementsByClassName("mySlides");
            if (n > x.length) {slideIndex = 1}
            if (n < 1) {slideIndex = x.length} ;
            for (i = 0; i < x.length; i++) {
                x[i].style.display = "none";
            }

            if (x.length > 0)
            {
                x[slideIndex-1].style.display = "block";
            }

            if(slideIndex==1)
            {
                jQuery("#titletext").show();
            }
            else
            {
                jQuery("#titletext").hide();
            }
        }
        function changeprodtoleft(prodId) {
            jQuery(".insta-popup-product-view-left-img img").css('opacity', '0.4');
            jQuery("#popprdloadingdiv").css('display', 'block');
            var formurl = '<?php echo $block->getPopupChangeProductUrl(); ?>';
            jQuery.ajax({
                type: "GET",
                url: formurl,
                data: {id: prodId},
                dataType: "json",
                showLoader: true,
                async: false,
                success: function (transport) {
                    jQuery("#popprdloadingdiv").css('display', 'none');
                    jQuery(".insta-popup-product-view-left-img img").css('opacity', '1');
                    var response = transport || "no response text";
                    jQuery(".insta-popup-product-view-left-img img").attr('src', response['prodimg']);
                    jQuery(".insta-popup-product-view-left-img a").attr('href', response['produrl']);
                    jQuery(".popup-img-desc .instatitle").text(response['prodname']);
                    jQuery(".popup-img-desc .popup-img-desc-part").text(response['proddesc']);

                    jQuery(".fb-share-link").attr("href", "https://www.facebook.com/sharer/sharer.php?u=" + response["produrl"] + "&t=" + response["prodname"]);
                    jQuery(".tiwtter-share-link").attr("href", "https://twitter.com/share?url=" + response['produrl'] + "&text=" + response['prodname']);
                    jQuery(".linkedin-share-link").attr("href", "https://www.linkedin.com/shareArticle?mini=true&url=" + response['produrl'] + "&title=" + response['prodname']);


                },
                error: function () {
                    jQuery("#popprdloadingdiv").css('display', 'none');
                    jQuery(".insta-popup-product-view-left-img img").css('opacity', '1');
                    alert('Something went wrong...');
                }
            });
        }



    </script>
<?php endif; ?>
