<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
?>

<?php
$width = (int)$block->getBackgroundImageWidth() ?: 1000;
$widthSmall = (int)$block->getSmallBackgroundImageWidth() ?: 350;
$imageHelper = $this->helper(\Magefan\Blog\Helper\Image::class);
?>

<?php
    $_postCollection = $block->getPostCollection();
    $count = (int) $_postCollection->count();
    $leftcount = (int)ceil(abs($count-2)/15);
?>

<?php if ($count) { ?>
    <?= $block->getStyleViewModel()->getStyle('Magefan_Blog::css/bootstrap-4.4.1-custom-min.css') ?>
    <?= $block->getStyleViewModel()->getStyle('Magefan_BlogExtra::css/template-all.css') ?>
    <?= $block->getStyleViewModel()->getStyle('Magefan_BlogExtra::css/template-4.css') ?>
    <?= $block->getStyleViewModel()->getStyle('Magefan_BlogExtra::css/template-4.2.css') ?>
    <?php
        $posts = [];
        foreach ($_postCollection as $post) {
            $posts[] = $post;
        }
    ?>

    <!-- Template 4-2 One Column Horizontal -->
    <div class="template-4-2 mb-5">
        <div class="block-inner">
            <!-- block title -->
            <?php if ($block->getTitle()) { ?>
                <div class="block-title-wrap">
                    <h4 class="block-title m-0"><?= $block->escapeHtml($block->getTitle()) ?></h4>
                </div>
            <?php } ?>

            <!-- block content -->
            <div class="block-content d-flex flex-column flex-md-row">
                <!-- block left -->
                <div class="block-left">
                    <?php for ($i = 0; $i<$leftcount; $i++ ) { ?>
                        <?php
                        $_post = $posts[$i];
                        $_postUrl = $block->escapeUrl($_post->getPostUrl());
                        $_postName = $block->escapeHtml($_post->getTitle());
                        ?>
                    <div class="block-wrap px-md-4 mb-4 mb-md-0">
                        <!-- block post -->
                        <div class="block-post">
                            <!-- img container -->
                            <div class="image-container mb-3">
                                <!-- post image -->
                                <a class="image-wrap" href="<?= /*@noEscape*/ $_postUrl ?>" title="<?= /*@noEscape*/ $_postName ?>">
                                    <?php
                                    $featuredImage = $_post->getFeaturedListImg() ?: $_post->getFeaturedImg();
                                    if ($featuredImage) {
                                        $featuredImage = $imageHelper->init($featuredImage)->resize($width, null, false);
                                        $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                                        if (!$featuredImgAlt) {
                                            $featuredImgAlt = $_postName;
                                        }
                                    } else {
                                        $featuredImage = $this->getViewFileUrl('Magefan_BlogExtra::images/default-no-image.png');
                                        $featuredImgAlt  = '';
                                    }
                                    ?>
                                    <div class="animation-type-zoom bg-img mfblogunveil" data-original="<?= $block->escapeHtml($featuredImage) ?>"></div>
                                </a>
                                <!-- post category-->
                                <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
                                    <span class="post-category m-0">
                                            <?php foreach ($_post->getParentCategories() as $ct) { ?>
                                                <a class="category-name"
                                                   href="<?= $block->escapeUrl($ct->getCategoryUrl()) ?>"
                                                   title="<?= $block->escapeHtml($ct->getTitle()) ?>">
                                                <?= $block->escapeHtml($ct->getTitle()) ?>
                                            </a>
                                            <?php } ?>
                                        </span>
                                <?php } ?>
                                <!-- end post category-->
                            </div>

                            <!-- block info -->
                            <div class="post-info">
                                <!-- post title -->
                                <div class="post-title-wrap mb-1">
                                    <h3 class="post-title m-0">
                                        <a href="<?= /*@noEscape*/ $_postUrl ?>"><?= /*@noEscape*/ $_postName ?></a>
                                    </h3>
                                </div>

                                <!-- block data -->
                                <div class="post-data-wrap mb-3">
                                    <!-- post author -->
                                    <?php if ($block->authorEnabled()) { ?>
                                        <?php if ($_author = $_post->getAuthor()) { ?>
                                            <span class="post-author">
                                            <?php if ($block->authorPageEnabled()) { ?>
                                                <a title="<?= $block->escapeHtml($_author->getTitle()) ?>"
                                                   href="<?= $block->escapeUrl($_author->getAuthorUrl()) ?>"><?= $block->escapeHtml($_author->getTitle()) ?>
                                                </a>
                                            <?php } else { ?>
                                                <?= $block->escapeHtml($_author->getTitle()) ?>
                                            <?php } ?>
                                            <span>-</span>
                                        </span>
                                        <?php } ?>
                                    <?php } ?>

                                    <!-- post data -->
                                    <?php if ($_post->isPublishDateEnabled()) { ?>
                                        <span class="post-data"><?= $block->escapeHtml($_post->getPublishDate()) ?></span>
                                    <?php } ?>

                                    <!-- post view -->
                                    <?php if ($_post->getCommentsCount()) { ?>
                                        <?php if ($commentCount = $_post->getCommentsCount()) { ?>
                                            <span class="post-view float-right">
                                                <?= $block->escapeHtml($commentCount)?>
                                            </span>
                                        <?php } ?>
                                    <?php } ?>
                                </div>

                                <!-- post description -->
                                <div class="post-description">
                                    <?= /*@noEscape*/ $_post->getShortFilteredContent() ?>
                                </div>
                            </div>
                        </div>
                        <!-- END block post -->
                    </div>
                    <?php } ?>
                </div>

                <?php if ($count > 1) { ?>
                    <!-- block right -->
                    <div class="block-right ">
                        <div class="block-wrap px-md-4">
                            <!-- post list -->
                            <div class="post-list _d-flex _flex-wrap _row-cols-md-2">
                                <?php foreach ($posts as $i => $_post) { ?>
                                    <?php if ( $i < $leftcount) continue; ?>
                                    <?php
                                        $_postUrl = $block->escapeUrl($_post->getPostUrl());
                                        $_postName = $block->escapeHtml($_post->getTitle());
                                    ?>
                                    <!-- post item -->
                                    <div class="post-item d-flex mb-4">
                                        <!-- img container -->
                                        <div class="image-container">
                                            <!-- post image -->
                                            <a class="image-wrap _4x3" href="<?= /*@noEscape*/ $_postUrl ?>" title="<?= /*@noEscape*/ $_postName ?>">
                                                <?php
                                                $featuredImage = $_post->getFeaturedListImg() ?: $_post->getFeaturedImg();
                                                if ($featuredImage) {
                                                    $featuredImage = $imageHelper->init($featuredImage)->resize($widthSmall, null, false);
                                                    $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                                                    if (!$featuredImgAlt) {
                                                        $featuredImgAlt = $_postName;
                                                    }
                                                } else {
                                                    $featuredImage = $this->getViewFileUrl('Magefan_BlogExtra::images/default-no-image.png');
                                                    $featuredImgAlt  = '';
                                                }
                                                ?>
                                                <div class="animation-type-zoom bg-img mfblogunveil" data-original="<?= $block->escapeHtml($featuredImage) ?>"></div>
                                            </a>
                                        </div>

                                        <!-- block info -->
                                        <div class="post-info">
                                            <!-- post title -->
                                            <div class="post-title-wrap mb-2">
                                                <h3 class="post-title m-0">
                                                    <a class="post-link" href="<?= /*@noEscape*/ $_postUrl ?>"><?= /*@noEscape*/ $_postName ?></a>
                                                </h3>
                                            </div>
                                            <!-- post data -->
                                            <?php if ($_post->isPublishDateEnabled()) { ?>
                                                <div class="block-date">
                                                    <span class="post-data"><?= $block->escapeHtml($_post->getPublishDate()) ?></span>
                                                </div>
                                            <?php } ?>
                                        </div>
                                    </div>
                                    <!-- END post item -->
                                <?php } ?>
                            </div>
                            <!-- END post list -->
                        </div>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
    <?= $block->getToolbarHtml() ?>
<?php } ?>