<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
?>

<?php
$width = (int)$block->getBackgroundImageWidth() ?: 1000;
$widthSmall = (int)$block->getSmallBackgroundImageWidth() ?: 350;
$imageHelper = $this->helper(\Magefan\Blog\Helper\Image::class);
?>

<?php
    $_postCollection = $block->getPostCollection();
    $count = (int) $_postCollection->count();
?>

<?php if ($count) { ?>
    <?= $block->getStyleViewModel()->getStyle('Magefan_Blog::css/bootstrap-4.4.1-custom-min.css') ?>
    <?= $block->getStyleViewModel()->getStyle('Magefan_BlogExtra::css/template-all.css') ?>
    <?= $block->getStyleViewModel()->getStyle('Magefan_BlogExtra::css/template-4.css') ?>
    <?= $block->getStyleViewModel()->getStyle('Magefan_BlogExtra::css/template-4.1.css') ?>
    <?php
        $leftcount = (int)ceil(abs($count-2)/6);

        $posts = [];
        foreach ($_postCollection as $post) {
            $posts[] = $post;
        }
    ?>

    <!-- Template 4-1 One Column Horizontal -->
    <div class="template-4-1 mb-3">
        <div class="block-inner">
            <!-- block title -->
            <?php if ($block->getTitle()) { ?>
                <div class="block-title-wrap">
                    <h4 class="block-title m-0"><a href="/blog"><?= $block->escapeHtml($block->getTitle()) ?></a></h4>
                    <h6>Explore some of our latest articles</h6>
                </div>
            <?php } ?>

            <!-- block content -->
            <div class="block-content flex">
                <!-- block left -->
                <div class="block-left">
                    <?php for ($i = 0; $i < $leftcount; $i++ ) { ?>
                            <?php
                            $_post = $posts[$i];
                            $_postUrl = $block->escapeUrl($_post->getPostUrl());
                            $_postName = $block->escapeHtml($_post->getTitle());
                            ?>
                    <div class="block-wrap">
                        <!-- block post -->
                        <div class="block-post">
                            <!-- img container -->
                            <div class="image-container">
                                <!-- post image -->
                                <a class="image-wrap block w-full" href="<?= /*@noEscape*/ $_postUrl ?>" title="<?= /*@noEscape*/ $_postName ?>">
                                    <?php
                                    $featuredImage = $_post->getFeaturedListImg() ?: $_post->getFeaturedImg();
                                    if ($featuredImage) {
                                        $featuredImage = $imageHelper->init($featuredImage)->resize($width, null, false);
                                        $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                                        if (!$featuredImgAlt) {
                                            $featuredImgAlt = $_postName;
                                        }
                                    } else {
                                        $featuredImage = $this->getViewFileUrl('Magefan_BlogExtra::images/default-no-image.png');
                                        $featuredImgAlt  = '';
                                    }
                                    ?>
                                    <div class="animation-type-zoom bg-img mfblogunveil" data-original="<?= $block->escapeHtml($featuredImage) ?>"></div>
                                </a>
                               
                            </div>

                            <!-- block info -->
                            <div class="post-info">
                                <div class="post-date flex flex-wrap justify-between items-center">
                                 <!-- post category-->
                                 <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
                                        <span class="post-category">
                                            <?php foreach ($_post->getParentCategories() as $ct) { ?>
                                            <a class="category-name"
                                               href="<?= $block->escapeUrl($ct->getCategoryUrl()) ?>"
                                               title="<?= $block->escapeHtml($ct->getTitle()) ?>">
                                                <?= $block->escapeHtml($ct->getTitle()) ?>
                                            </a>
                                            <?php } ?>
                                        </span>
                                <?php } ?>
                                <!-- end post category-->
                                <div class="data-author-detials flex">
                                <!-- post author -->
                                <?php if ($block->authorEnabled()) { ?>
                                        <?php if ($_author = $_post->getAuthor()) { ?>
                                            <span class="post-author">
                                            <?php if ($block->authorPageEnabled()) { ?>
                                                <a class="capitalize" title="<?= $block->escapeHtml($_author->getTitle()) ?>"
                                                   href="<?= $block->escapeUrl($_author->getAuthorUrl()) ?>"><?= $block->escapeHtml($_author->getTitle()) ?>
                                                </a>
                                            <?php } else { ?>
                                                <?= $block->escapeHtml($_author->getTitle()) ?>
                                            <?php } ?>
                                            <span class="mr-1">|</span>
                                        </span>
                                        <?php } ?>
                                    <?php } ?>

                                    <!-- post data -->
                                    <?php if ($_post->isPublishDateEnabled()) { ?>
                                        <span class="post-data uppercase"><?= $block->escapeHtml($_post->getPublishDate()) ?></span>
                                    <?php } ?>
                                </div>
                                </div>
                                <!-- post title -->
                                <div class="post-title-wrap">
                                    <h3 class="post-title">
                                        <a href="<?= /*@noEscape*/ $_postUrl ?>"><?= /*@noEscape*/ $_postName ?></a>
                                    </h3>
                                </div>

                                <!-- block data -->
                                <div class="post-data-wrap">
                                    

                                    <!-- post view -->
                                    <?php if ($_post->getCommentsCount()) { ?>
                                        <?php if ($commentCount = $_post->getCommentsCount()) { ?>
                                            <span class="post-view float-right">
                                                <?= $block->escapeHtml($commentCount)?>
                                            </span>
                                        <?php } ?>
                                    <?php } ?>
                                </div>

                                <!-- post description -->
                                <div class="post-description">
                                    <?= /*@noEscape*/ $_post->getShortFilteredContent() ?>
                                </div>
                                <span class="read-more"><a href="<?= /*@noEscape*/ $_postUrl ?>">Learn More</a></span>
                            </div>
                        </div>
                        <!-- END block post -->
                    </div>
                    <?php } ?>
                </div>

                <div class="block-right ">
                        <div class="block-wrap">
                            <?php
                                echo $this->getLayout()
                                ->createBlock('Magento\Cms\Block\Block')
                                ->setBlockId('home_blog_middle')
                                ->toHtml();
                            ?>
                        </div>
                </div>
                
            </div>
        </div>
    </div>
    <?= $block->getToolbarHtml() ?>
<?php } ?>