<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
?>

<?php
$width = (int)$block->getBackgroundImageWidth() ?: 1000;
$imageHelper = $this->helper(\Magefan\Blog\Helper\Image::class);
?>

<?php
    $_postCollection = $block->getPostCollection();
    $count = (int) $_postCollection->count();
?>

<?php if ($count) { ?>
    <?= $block->getStyleViewModel()->getStyle('Magefan_Blog::css/bootstrap-4.4.1-custom-min.css') ?>
    <?= $block->getStyleViewModel()->getStyle('Magefan_BlogExtra::css/mosaica-all.css') ?>
    <?= $block->getStyleViewModel()->getStyle('Magefan_BlogExtra::css/mosaica-2.css') ?>
    <?php
        $posts = [];
        foreach ($_postCollection as $post) {
            $posts[] = $post;
        }
    ?>
    <?php $iteration = 0; ?>
    <?php for ($i = 0; $i < $count; $i += 5) { ?>
        <?php
            $iteration++;
            $maxCount = $count - $i;
            if ($maxCount > 5) {
                $maxCount = 5;
            }

            $_post = $posts[0 + $i];
            $_postUrl = $block->escapeUrl($_post->getPostUrl());
            $_postName = $block->escapeHtml($_post->getTitle());
        ?>
        <div class="mosaica-2 mb-5 items-count-<?= $maxCount ?> clear">

            <!-- block title -->
            <?php if (1 == $iteration && $block->getTitle()) { ?>
                <div class="block-title-wrap">
                    <h4 class="block-title m-0"><?= $block->escapeHtml($block->getTitle()) ?></h4>
                </div>
            <?php } ?>

            <?php
            if (1 == $maxCount) {
                $rows = 1;
            } else if ($maxCount < 4) {
                $rows = 2;
            } else {
                $rows = 3;
            }
            ?>
            <div class="block-inner d-flex _row-cols-3 row-cols-<?= $rows ?>">

                <div class="m-block-left">
                    <div class="post-block post-top position-relative">
                        <div class="image-container">
                            <a class="image-wrap" href="<?= /*@noEscape*/ $_postUrl ?>"  title="<?= /*@noEscape*/ $_postName ?>">
                                <?php
                                $featuredImage = $_post->getFeaturedListImg() ?: $_post->getFeaturedImg();
                                if ($featuredImage) {
                                    $featuredImage = $imageHelper->init($featuredImage)->resize($width, null, false);
                                    $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                                    if (!$featuredImgAlt) {
                                        $featuredImgAlt = $_postName;
                                    }
                                } else {
                                    $featuredImage = $this->getViewFileUrl('Magefan_BlogExtra::images/default-no-image.png');
                                    $featuredImgAlt  = '';
                                }
                                ?>
                                <div class="animation-type-zoom bg-img mfblogunveil" data-original="<?= $block->escapeHtml($featuredImage) ?>"></div>
                            </a>
                        </div>
                        <div class="post-info p-4 mb-0">

                            <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
                                <?php foreach ($_post->getParentCategories() as $ct) { ?>
                                    <a title="<?= $block->escapeHtml($ct->getTitle()) ?>" href="<?= $block->escapeUrl($ct->getCategoryUrl()) ?>" class="post-category"><?= $block->escapeHtml($ct->getTitle()) ?></a>
                                <?php } ?>
                            <?php } ?>

                            <div class="post-title-wrap">
                                <h3 class="post-title">
                                    <a href="<?= /*@noEscape*/ $_postUrl ?>"><?= /*@noEscape*/ $_postName ?></a>
                                </h3>
                            </div>
                            <!-- block data -->
                            <div class="post-data-wrap d-none">
                                <!-- post author -->
                                <?php if ($block->authorEnabled()) { ?>
                                    <?php if ($_author = $_post->getAuthor()) { ?>
                                        <span class="post-author">
                                            <?php if ($block->authorPageEnabled()) { ?>
                                                <a title="<?= $block->escapeHtml($_author->getTitle()) ?>"
                                                   href="<?= $block->escapeUrl($_author->getAuthorUrl()) ?>"><?= $block->escapeHtml($_author->getTitle()) ?>
                                                </a>
                                            <?php } else { ?>
                                                <?= $block->escapeHtml($_author->getTitle()) ?>
                                            <?php } ?>
                                                <span>-</span>
                                            </span>
                                    <?php } ?>
                                <?php } ?>

                                <!-- post data -->
                                <?php if ($_post->isPublishDateEnabled()) { ?>
                                    <span class="post-data"><?= $block->escapeHtml($_post->getPublishDate()) ?></span>
                                <?php } ?>
                            </div>
                        </div>
                    </div>

                    <?php if ($count > 1 && array_key_exists(1 + $i, $posts)) { ?>
                        <?php
                        $_post = $posts[1 + $i];
                        $_postUrl = $block->escapeUrl($_post->getPostUrl());
                        $_postName = $block->escapeHtml($_post->getTitle());
                        ?>
                        <div class="post-block post-bottom position-relative">
                            <div class="image-container">
                                <a class="image-wrap" href="<?= /*@noEscape*/ $_postUrl ?>"  title="<?= /*@noEscape*/ $_postName ?>">
                                    <?php
                                    $featuredImage = $_post->getFeaturedListImg() ?: $_post->getFeaturedImg();
                                    if ($featuredImage) {
                                        $featuredImage = $imageHelper->init($featuredImage)->resize($width, null, false);
                                        $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                                        if (!$featuredImgAlt) {
                                            $featuredImgAlt = $_postName;
                                        }
                                    } else {
                                        $featuredImage = $this->getViewFileUrl('Magefan_BlogExtra::images/default-no-image.png');
                                        $featuredImgAlt  = '';
                                    }
                                    ?>
                                    <div class="animation-type-zoom bg-img mfblogunveil" data-original="<?= $block->escapeHtml($featuredImage) ?>"></div>
                                </a>
                            </div>
                            <div class="post-info p-4 mb-0">

                                <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
                                    <?php foreach ($_post->getParentCategories() as $ct) { ?>
                                        <a title="<?= $block->escapeHtml($ct->getTitle()) ?>" href="<?= $block->escapeUrl($ct->getCategoryUrl()) ?>" class="post-category"><?= $block->escapeHtml($ct->getTitle()) ?></a>
                                    <?php } ?>
                                <?php } ?>

                                <div class="post-title-wrap">
                                    <h3 class="post-title">
                                        <a href="<?= /*@noEscape*/ $_postUrl ?>"><?= /*@noEscape*/ $_postName ?></a>
                                    </h3>
                                </div>
                                <!-- block data -->
                                <div class="post-data-wrap d-none">
                                    <!-- post author -->
                                    <?php if ($block->authorEnabled()) { ?>
                                        <?php if ($_author = $_post->getAuthor()) { ?>
                                            <span class="post-author">
                                            <?php if ($block->authorPageEnabled()) { ?>
                                                <a title="<?= $block->escapeHtml($_author->getTitle()) ?>"
                                                   href="<?= $block->escapeUrl($_author->getAuthorUrl()) ?>"><?= $block->escapeHtml($_author->getTitle()) ?>
                                                </a>
                                            <?php } else { ?>
                                                <?= $block->escapeHtml($_author->getTitle()) ?>
                                            <?php } ?>
                                                <span>-</span>
                                            </span>
                                        <?php } ?>
                                    <?php } ?>

                                    <!-- post data -->
                                    <?php if ($_post->isPublishDateEnabled()) { ?>
                                        <span class="post-data"><?= $block->escapeHtml($_post->getPublishDate()) ?></span>
                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                </div>


                <?php if ($count > 2 &&  array_key_exists(2 + $i, $posts)) {  ?>
                    <?php
                    $_post = $posts[2 + $i];
                    $_postUrl = $block->escapeUrl($_post->getPostUrl());
                    $_postName = $block->escapeHtml($_post->getTitle());
                    ?>
                    <div class="m-block-center">
                        <div class="post-block position-relative ">
                            <div class="image-container">
                                <!-- post image -->
                                <a class="image-wrap" href="<?= /*@noEscape*/ $_postUrl ?>" title="<?= /*@noEscape*/ $_postName ?>">
                                    <?php
                                    $featuredImage = $_post->getFeaturedListImg() ?: $_post->getFeaturedImg();
                                    if ($featuredImage) {
                                        $featuredImage = $imageHelper->init($featuredImage)->resize($width, null, false);
                                        $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                                        if (!$featuredImgAlt) {
                                            $featuredImgAlt = $_postName;
                                        }
                                    } else {
                                        $featuredImage = $this->getViewFileUrl('Magefan_BlogExtra::images/default-no-image.png');
                                        $featuredImgAlt  = '';
                                    }
                                    ?>
                                    <div class="animation-type-zoom bg-img mfblogunveil" data-original="<?= $block->escapeHtml($featuredImage) ?>"></div>
                                </a>
                            </div>
                            <div class="post-info p-4 mb-0">
                                <!-- post category-->
                                <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
                                    <?php foreach ($_post->getParentCategories() as $ct) { ?>
                                        <a title="<?= $block->escapeHtml($ct->getTitle()) ?>" href="<?= $block->escapeUrl($ct->getCategoryUrl()) ?>" class="post-category"><?= $block->escapeHtml($ct->getTitle()) ?></a>
                                    <?php } ?>
                                <?php } ?>
                                <!-- end post category-->

                                <!-- post title -->
                                <div class="post-title-wrap mb-3">
                                    <h3 class="post-title">
                                        <a href="<?= /*@noEscape*/ $_postUrl ?>"><?= /*@noEscape*/ $_postName ?></a>
                                    </h3>
                                </div>
                                <!-- block data -->
                                <div class="post-data-wrap">
                                    <!-- post author -->
                                    <?php if ($block->authorEnabled()) { ?>
                                        <?php if ($_author = $_post->getAuthor()) { ?>
                                            <span class="post-author">
                                            <?php if ($block->authorPageEnabled()) { ?>
                                                <a title="<?= $block->escapeHtml($_author->getTitle()) ?>"
                                                   href="<?= $block->escapeUrl($_author->getAuthorUrl()) ?>"><?= $block->escapeHtml($_author->getTitle()) ?>
                                                </a>
                                            <?php } else { ?>
                                                <?= $block->escapeHtml($_author->getTitle()) ?>
                                            <?php } ?>
                                            <span>-</span>
                                        </span>
                                        <?php } ?>
                                    <?php } ?>

                                    <!-- post data -->
                                    <?php if ($_post->isPublishDateEnabled()) { ?>
                                        <span class="post-data"><?= $block->escapeHtml($_post->getPublishDate()) ?></span>
                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } ?>

                <?php if ($count > 3 &&  array_key_exists(3 + $i, $posts)) { ?>
                    <?php
                    $_post = $posts[3 + $i];
                    $_postUrl = $block->escapeUrl($_post->getPostUrl());
                    $_postName = $block->escapeHtml($_post->getTitle());
                    ?>
                    <div class="m-block-right">
                        <div class="post-block post-top position-relative">
                            <div class="image-container">
                                <a class="image-wrap" href="<?= /*@noEscape*/ $_postUrl ?>"  title="<?= /*@noEscape*/ $_postName ?>">
                                    <?php
                                    $featuredImage = $_post->getFeaturedListImg() ?: $_post->getFeaturedImg();
                                    if ($featuredImage) {
                                        $featuredImage = $imageHelper->init($featuredImage)->resize($width, null, false);
                                        $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                                        if (!$featuredImgAlt) {
                                            $featuredImgAlt = $_postName;
                                        }
                                    } else {
                                        $featuredImage = $this->getViewFileUrl('Magefan_BlogExtra::images/default-no-image.png');
                                        $featuredImgAlt  = '';
                                    }
                                    ?>
                                    <div class="animation-type-zoom bg-img mfblogunveil" data-original="<?= $block->escapeHtml($featuredImage) ?>"></div>
                                </a>
                            </div>
                            <div class="post-info p-4 mb-0">

                                <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
                                    <?php foreach ($_post->getParentCategories() as $ct) { ?>
                                        <a title="<?= $block->escapeHtml($ct->getTitle()) ?>" href="<?= $block->escapeUrl($ct->getCategoryUrl()) ?>" class="post-category"><?= $block->escapeHtml($ct->getTitle()) ?></a>
                                    <?php } ?>
                                <?php } ?>

                                <div class="post-title-wrap">
                                    <h3 class="post-title">
                                        <a href="<?= /*@noEscape*/ $_postUrl ?>"><?= /*@noEscape*/ $_postName ?></a>
                                    </h3>
                                </div>
                                <!-- block data -->
                                <div class="post-data-wrap">
                                    <!-- post author -->
                                    <?php if ($block->authorEnabled()) { ?>
                                        <?php if ($_author = $_post->getAuthor()) { ?>
                                            <span class="post-author">
                                            <?php if ($block->authorPageEnabled()) { ?>
                                                <a title="<?= $block->escapeHtml($_author->getTitle()) ?>"
                                                   href="<?= $block->escapeUrl($_author->getAuthorUrl()) ?>"><?= $block->escapeHtml($_author->getTitle()) ?>
                                                </a>
                                            <?php } else { ?>
                                                <?= $block->escapeHtml($_author->getTitle()) ?>
                                            <?php } ?>
                                                <span>-</span>
                                            </span>
                                        <?php } ?>
                                    <?php } ?>

                                    <!-- post data -->
                                    <?php if ($_post->isPublishDateEnabled()) { ?>
                                        <span class="post-data"><?= $block->escapeHtml($_post->getPublishDate()) ?></span>
                                    <?php } ?>
                                </div>
                            </div>
                        </div>

                        <?php if ($count > 4 & array_key_exists(4 + $i, $posts)) { ?>
                            <?php
                            $_post = $posts[4 + $i];
                            $_postUrl = $block->escapeUrl($_post->getPostUrl());
                            $_postName = $block->escapeHtml($_post->getTitle());
                            ?>
                            <div class="post-block post-bottom position-relative">
                                <div class="image-container">
                                    <a class="image-wrap" href="<?= /*@noEscape*/ $_postUrl ?>"  title="<?= /*@noEscape*/ $_postName ?>">
                                        <?php
                                        $featuredImage = $_post->getFeaturedListImg() ?: $_post->getFeaturedImg();
                                        if ($featuredImage) {
                                            $featuredImage = $imageHelper->init($featuredImage)->resize($width, null, false);
                                            $featuredImgAlt = $_post->getData('featured_list_img_alt') ?: $_post->getData('featured_img_alt');
                                            if (!$featuredImgAlt) {
                                                $featuredImgAlt = $_postName;
                                            }
                                        } else {
                                            $featuredImage = $this->getViewFileUrl('Magefan_BlogExtra::images/default-no-image.png');
                                            $featuredImgAlt  = '';
                                        }
                                        ?>
                                        <div class="animation-type-zoom bg-img mfblogunveil" data-original="<?= $block->escapeHtml($featuredImage) ?>"></div>
                                    </a>
                                </div>
                                <div class="post-info p-4 mb-0">

                                    <?php if ($_categoriesCount = $_post->getCategoriesCount()) { ?>
                                        <?php foreach ($_post->getParentCategories() as $ct) { ?>
                                            <a title="<?= $block->escapeHtml($ct->getTitle()) ?>" href="<?= $block->escapeUrl($ct->getCategoryUrl()) ?>" class="post-category"><?= $block->escapeHtml($ct->getTitle()) ?></a>
                                        <?php } ?>
                                    <?php } ?>

                                    <div class="post-title-wrap">
                                        <h3 class="post-title">
                                            <a href="<?= /*@noEscape*/ $_postUrl ?>"><?= /*@noEscape*/ $_postName ?></a>
                                        </h3>
                                    </div>
                                    <!-- block data -->
                                    <div class="post-data-wrap d-none">
                                        <!-- post author -->
                                        <?php if ($block->authorEnabled()) { ?>
                                            <?php if ($_author = $_post->getAuthor()) { ?>
                                                <span class="post-author">
                                            <?php if ($block->authorPageEnabled()) { ?>
                                                <a title="<?= $block->escapeHtml($_author->getTitle()) ?>"
                                                   href="<?= $block->escapeUrl($_author->getAuthorUrl()) ?>"><?= $block->escapeHtml($_author->getTitle()) ?>
                                                </a>
                                            <?php } else { ?>
                                                <?= $block->escapeHtml($_author->getTitle()) ?>
                                            <?php } ?>
                                                <span>-</span>
                                            </span>
                                            <?php } ?>
                                        <?php } ?>

                                        <!-- post data -->
                                        <?php if ($_post->isPublishDateEnabled()) { ?>
                                            <span class="post-data"><?= $block->escapeHtml($_post->getPublishDate()) ?></span>
                                        <?php } ?>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                <?php } ?>

            </div>
        </div>
        <!-- END Mosaica -->
    <?php } ?>
    <?= $block->getToolbarHtml() ?>
<?php } ?>