<?php
declare(strict_types=1);
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_HyvaCompatBase
 * @author     Extension Team
 * @copyright  Copyright (c) 2022 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\CustomerRegistration;
use Magento\Customer\Block\Account\Customer;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\Customer as CustomerNew;

/** @var Customer $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var CustomerRegistration $customerRegistration */
$customerRegistration = $viewModels->require(CustomerRegistration::class);

$customer = $viewModels->require(CustomerNew::class);
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
?>
<script>
"use strict";

function initComponent() {
  return {
    cart: false,
    customer: false,
    receiveCustomerData(data) {
      if (data.cart) {
        this.cart = data.cart;
      }
      if (data.customer) {
        this.customer = data.customer;
      }
    }
  }
}
</script>


<div x-data="{ open: false }" class="relative inline-block acc-dropdown">
<?php if ($customer->customerLoggedIn()): ?>
    <div class="arrow-dropdown">
    <?php endif ?>
    <?php if (!$customer->customerLoggedIn()): ?>
    <div class="arrow-cus">
    <?php endif ?>
    <a
        href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($block->getUrl('customer/account'))) ?>"
        id="customer-menu"
        class="block hover:text-black "
        <?php if (!$customer->customerLoggedIn()): ?>
            @click.prevent="$dispatch('popup-register',
                { open: true,openRegister : false,openLogin : true,openCreate :true,
                openButtonLogin :true,
                openButtonRegister :false,
            })"
        <?php else: ?>
            @click.prevent="open = true"
        <?php endif ?>
        :aria-expanded="open ? 'true' : 'false'"
        aria-label="<?= $escaper->escapeHtmlAttr(__('My Account')) ?>"
    >
    <?php if (!$customer->customerLoggedIn()): ?>
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor"
             class="w-8 h-8 md:h-6 md:w-6" aria-hidden="true">
            <circle fill="none" cx="12" cy="7" r="3"></circle>
            <path d="M12 2C9.243 2 7 4.243 7 7s2.243 5 5 5 5-2.243 5-5S14.757 2 12 2zM12 10c-1.654
                0-3-1.346-3-3s1.346-3 3-3 3 1.346 3 3S13.654 10 12 10zM21 21v-1c0-3.859-3.141-7-7-7h-4c-3.86
                0-7 3.141-7 7v1h2v-1c0-2.757 2.243-5 5-5h4c2.757 0 5 2.243 5 5v1H21z">
            </path>
        </svg>
    <?php else: ?>
        <div x-data="initComponent()"
     @private-content-loaded.window="receiveCustomerData($event.detail.data)"
>
  <template x-if="customer">
    <div>Hello, <span x-text="customer.fullname"></span></div>
  </template>
</div>
    <?php endif ?>       
    </a>
    <?php if (!$customer->customerLoggedIn()): ?>
    </div>
    <?php endif ?>
    <?php if ($customer->customerLoggedIn()): ?>
    </div>
    <?php endif ?>
    <nav class="absolute right-0 z-20 hidden w-40 pt-3 pb-4 mt-2 -mr-4 pl-4 pr-4 overflow-auto origin-top-right rounded-sm
        shadow-lg sm:w-48 lg:mt-3 bg-container-lighter"
         :class="{ 'hidden' : !open }"
         @click.outside="open = false"
         x-cloak x-show="open"
         aria-labelledby="customer-menu"
    >
        <?php if ($block->customerLoggedIn()): ?>
            <?= $block->getChildHtml('customer_logged-menu') ?>
        <?php else: ?>
            <?= $block->getChildHtml('customer_not-login-menu') ?>
        <?php endif; ?>
    </nav>
</div>