<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\ProductListItem;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\Store;
use Magento\Catalog\Block\Product\ReviewRendererInterface as ProductReviewRenderer;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Store $viewModelStore */
$viewModelStore = $viewModels->require(Store::class);

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var ProductListItem $productListItemViewModel */
$productListItemViewModel = $viewModels->require(ProductListItem::class);
$viewMode = 'grid';
$imageDisplayArea = 'category_page_grid';
$showDescription = false;
$title = (string) $block->getTitle();
$items = $block->getItems() ?? [];
if (is_object($items) && $items instanceof Iterator) {
    $items = iterator_to_array($items);
}
if (!$itemCount = count($items)) {
    return '';
}

$sliderItemRenderer = $block->getLayout()->getBlock('product_list_item')
    ?: $block->getChildBlock('slider.item.template')
    ?: $block->getLayout()->createBlock(Template::class);
$hideRatingSummary = (bool) $block->getData('hide_rating_summary');
$hideDetails       = (bool) $block->getData('hide_details');
$sliderItemRenderer->setData('hide_details', $hideDetails);
$sliderItemRenderer->setData('hide_rating_summary', $hideRatingSummary);

// The slider item renderer block is often a shared instance.
// If a specific item template is set for this slider, the previously set template must be reset later
// so the item template is only replaced for the one slider it is specified on.
$sharedItemRendererTemplate = null;
$isSharedItemRenderer       = $sliderItemRenderer !== $block->getChildBlock('slider.item.template');
if ($isSharedItemRenderer && $block->getChildBlock('slider.item.template')) {
    $sharedItemRendererTemplate = $sliderItemRenderer->getTemplate();
    $sliderSpecificItemTemplate = $block->getChildBlock('slider.item.template')->getTemplate();
    $sliderItemRenderer->setTemplate($sliderSpecificItemTemplate);
}
?>
<script>
    'use strict';
    function initSliderComponentRelatedPopup() {
        return {
            active: 0,
            itemCount: 0,
            getSlider() {
                return this.$root.querySelector('.products_slider_related_popup .js_slides');
            },
            pageSize: 3,
            pageFillers: 0,
            calcPageSize() {
                const slider = this.getSlider();
                if (slider) {
                    this.itemCount = slider.querySelectorAll('.products_slider_related_popup .js_slide').length;
                    //this.pageSize = Math.round(slider.clientWidth / slider.querySelector('.js_slide').clientWidth);
                    if (window.innerWidth >= 1280) {
                        this.pageSize = 3;
                    } else if (window.innerWidth >= 1024) {
                        this.pageSize = 3;
                    } else if (window.innerWidth >= 768) {
                        this.pageSize = 2;
                    } else {
                        this.pageSize = 1;
                    }
                       
                    this.pageFillers = (
                        this.pageSize * Math.ceil(this.itemCount / this.pageSize)
                    ) - this.itemCount;
                }
            },
            calcActive() {
                const slider = this.getSlider();
                if (slider) {
                    const sliderItems = this.itemCount + this.pageFillers;
                    const calculatedActiveSlide = slider.scrollLeft / (slider.scrollWidth / sliderItems);
                    this.active = Math.round(calculatedActiveSlide / this.pageSize) * this.pageSize;
                }
            },
            scrollPrevious() {
                this.scrollTo(this.active - this.pageSize);
            },
            scrollNext() {
                this.scrollTo(this.active + this.pageSize);
            },
            scrollTo(idx) {
                const slider = this.getSlider();
                if (slider) {
                    const slideWidth = slider.scrollWidth / (this.itemCount + this.pageFillers);
                    slider.scrollLeft = Math.floor(slideWidth) * idx;
                    this.active = idx;
                }
            }
        }
    }
</script>
<section  id="products_slider_related_popup"  class="<?=
    $escaper->escapeHtmlAttr($block->getData('maybe_purged_tailwind_section_classes'))
    ?: 'my-12 text-gray-700 body-font';?> products_slider products_slider_related_popup"  x-data="initSliderComponentRelatedPopup()"
x-init="calcPageSize();" @resize.window.debounce="calcPageSize(); $nextTick( function() { calcActive() })">

    <?php if ($items): ?>
        <div class="relative">
            <?php if ($title): ?>
                <div class="w-full flex flex-col items-center mx-auto md:flex-row">
                    <h5>
                        <?= $escaper->escapeHtml($title); ?>
                    </h5>
                </div>
            <?php endif; ?>
            <div class="flex-none relative w-full overflow-x-hidden">
                <div class="relative flex flex-nowrap w-full overflow-auto js_slides snap"
                     @scroll.debounce="calcActive"
                >
                    <?php foreach ($items as $product): ?>
                        <div class="flex shrink-0 w-full js_slide md:w-1/2 lg:w-1/3 xl:w-1/3">
                            <?= /** @noEscape */ $productListItemViewModel->getItemHtmlWithRenderer(
                                $sliderItemRenderer,
                                $product,
                                $block,
                                $viewMode,
                                ProductReviewRenderer::SHORT_VIEW,
                                $imageDisplayArea,
                                $showDescription
                            ) ?>
                        </div>
                    <?php endforeach; ?>
                    <div :class="{
                        'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/3 flex shrink-0 py-1' : pageFillers > 0
                        }"></div>
                    <div :class="{
                        'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/3 flex shrink-0 py-1' : pageFillers > 1
                        }"></div>
                    <div :class="{
                        'js_dummy_slide w-full md:w-1/2 lg:w-1/3 xl:w-1/3 flex shrink-0 py-1' : pageFillers > 2
                        }"></div>
                </div>
            </div>
            <div>
            <template x-if="itemCount > pageSize">
                <div class="flex items-center justify-center py-4 page">
                    <button
                        aria-label="<?= $escaper->escapeHtml(__('Previous')) ?>"
                        tabindex="-1"
                        class="mr-4 text-black rounded-full outline-none focus:outline-none flex-none btn-prev"
                        :class="{ 'opacity-25 pointer-events-none' : active === 0 }"
                        @click="scrollPrevious">
                        <?= $heroicons->chevronLeftHtml("w-5 h-5", 25, 25) ?>
                    </button>
                    <div class="flex flex-wrap w-full md:w-auto justify-center js_dots">
                    <?php for ($i=0; $i < $itemCount; $i++): ?>
                        <span class="shrink-0 block w-3 h-3 m-1 bg-black bg-opacity-25 rounded-full shadow cursor-pointer"
                                :class="{
                                    'bg-opacity-100': active === <?= (int) $i ?>,
                                    'hidden': (pageSize !== 1 && !!(<?= (int) $i ?> % pageSize))
                                    }"
                                @click="scrollTo(<?= (int) $i ?>)">
                        </span>
                    <?php endfor; ?>
                    </div>
                    <button
                        aria-label="<?= $escaper->escapeHtml(__('Next')) ?>"
                        tabindex="-1"
                        class="ml-4 text-black rounded-full outline-none focus:outline-none flex-none btn-next"
                        :class="{ 'opacity-25 pointer-events-none' : active >= itemCount-pageSize }"
                        @click="scrollNext">
                        <?= $heroicons->chevronRightHtml("w-5 h-5", 25, 25) ?>
                    </button>
                </div>
            </template>
            </div>
        </div>
    <?php endif; ?>
</section>
<?php

if ($sharedItemRendererTemplate) {
    $sliderItemRenderer->setTemplate($sharedItemRendererTemplate);
}

?>

<script type="text/javascript">
    /*var targetSpan1 = document.querySelector('span[x-text="total_qty_tile"]');
    // Create a MutationObserver instance
    var observer1 = new MutationObserver(function(mutations){
        mutations.forEach(function(mutation){
            // Handle the content change
            var newValue = mutation.target.textContent;
            var displayElements = document.querySelectorAll('.catalog-product-view .youMayAlso.products_slider .js_slide .compare-buttons .qty_fields .field.qty .input-text');
            displayElements.forEach(function (element) {
                element.value = newValue;
            });
        });
    });
    // Configure the observer to watch for changes in the text content
    var config1 = { childList: true, subtree: true, characterData: true };
    // Start observing the target span
    observer1.observe(targetSpan1, config1);
    // Simulate a dynamic change in content after a delay (for demonstration purposes)
    setTimeout(function(){
        targetSpan1.textContent = 'New Value';
    }, 0); */
	
	function addObserverIfDesiredNodeAvailable() {
		var composeBox = document.querySelector('span[x-text="total_qty_tile"]');
		if(!composeBox) {
			//The node we need does not exist yet.
			//Wait 500ms and try again
			window.setTimeout(addObserverIfDesiredNodeAvailable,500);
			return;
		}
		var observer1 = new MutationObserver(function(mutations){
        mutations.forEach(function(mutation){
            // Handle the content change
            var newValue = mutation.target.textContent;
            
            var displayElements = document.querySelectorAll('.catalog-product-view .youMayAlso.products_slider .js_slide .compare-buttons .qty_fields .field.qty .input-text')[2];
            displayElements.forEach(function (element) {
                element.value = newValue;
            });
        });
		});
		var config = {childList: true};
		observer1.observe(composeBox,config);
	}
addObserverIfDesiredNodeAvailable();
</script>